/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActIdInfoPjo implements Serializable {

    private static final long serialVersionUID = -192679919;

    private String  id_;
    private Integer rev_;
    private String  userId_;
    private String  type_;
    private String  key_;
    private String  value_;
    private byte[]  password_;
    private String  parentId_;

    public ActIdInfoPjo() {}

    public ActIdInfoPjo(ActIdInfoPjo value) {
        this.id_ = value.id_;
        this.rev_ = value.rev_;
        this.userId_ = value.userId_;
        this.type_ = value.type_;
        this.key_ = value.key_;
        this.value_ = value.value_;
        this.password_ = value.password_;
        this.parentId_ = value.parentId_;
    }

    public ActIdInfoPjo(
        String  id_,
        Integer rev_,
        String  userId_,
        String  type_,
        String  key_,
        String  value_,
        byte[]  password_,
        String  parentId_
    ) {
        this.id_ = id_;
        this.rev_ = rev_;
        this.userId_ = userId_;
        this.type_ = type_;
        this.key_ = key_;
        this.value_ = value_;
        this.password_ = password_;
        this.parentId_ = parentId_;
    }

    public String getId_() {
        return this.id_;
    }

    public ActIdInfoPjo setId_(String id_) {
        this.id_ = id_;
        return this;
    }

    public Integer getRev_() {
        return this.rev_;
    }

    public ActIdInfoPjo setRev_(Integer rev_) {
        this.rev_ = rev_;
        return this;
    }

    public String getUserId_() {
        return this.userId_;
    }

    public ActIdInfoPjo setUserId_(String userId_) {
        this.userId_ = userId_;
        return this;
    }

    public String getType_() {
        return this.type_;
    }

    public ActIdInfoPjo setType_(String type_) {
        this.type_ = type_;
        return this;
    }

    public String getKey_() {
        return this.key_;
    }

    public ActIdInfoPjo setKey_(String key_) {
        this.key_ = key_;
        return this;
    }

    public String getValue_() {
        return this.value_;
    }

    public ActIdInfoPjo setValue_(String value_) {
        this.value_ = value_;
        return this;
    }

    public byte[] getPassword_() {
        return this.password_;
    }

    public ActIdInfoPjo setPassword_(byte... password_) {
        this.password_ = password_;
        return this;
    }

    public String getParentId_() {
        return this.parentId_;
    }

    public ActIdInfoPjo setParentId_(String parentId_) {
        this.parentId_ = parentId_;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActIdInfoPjo (");

        sb.append(id_);
        sb.append(", ").append(rev_);
        sb.append(", ").append(userId_);
        sb.append(", ").append(type_);
        sb.append(", ").append(key_);
        sb.append(", ").append(value_);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(parentId_);

        sb.append(")");
        return sb.toString();
    }
}
