/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 菜单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MenuPjo implements Serializable {

    private static final long serialVersionUID = -1027315435;

    private BigDecimal id;
    private String     name;
    private String     pageUrl;
    private BigDecimal parentId;
    private Short      level;
    private Boolean    isHomepage;
    private Short      status;
    private BigDecimal createBy;
    private Timestamp  createAt;

    public MenuPjo() {}

    public MenuPjo(MenuPjo value) {
        this.id = value.id;
        this.name = value.name;
        this.pageUrl = value.pageUrl;
        this.parentId = value.parentId;
        this.level = value.level;
        this.isHomepage = value.isHomepage;
        this.status = value.status;
        this.createBy = value.createBy;
        this.createAt = value.createAt;
    }

    public MenuPjo(
        BigDecimal id,
        String     name,
        String     pageUrl,
        BigDecimal parentId,
        Short      level,
        Boolean    isHomepage,
        Short      status,
        BigDecimal createBy,
        Timestamp  createAt
    ) {
        this.id = id;
        this.name = name;
        this.pageUrl = pageUrl;
        this.parentId = parentId;
        this.level = level;
        this.isHomepage = isHomepage;
        this.status = status;
        this.createBy = createBy;
        this.createAt = createAt;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public MenuPjo setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public MenuPjo setName(String name) {
        this.name = name;
        return this;
    }

    public String getPageUrl() {
        return this.pageUrl;
    }

    public MenuPjo setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
        return this;
    }

    public BigDecimal getParentId() {
        return this.parentId;
    }

    public MenuPjo setParentId(BigDecimal parentId) {
        this.parentId = parentId;
        return this;
    }

    public Short getLevel() {
        return this.level;
    }

    public MenuPjo setLevel(Short level) {
        this.level = level;
        return this;
    }

    public Boolean getIsHomepage() {
        return this.isHomepage;
    }

    public MenuPjo setIsHomepage(Boolean isHomepage) {
        this.isHomepage = isHomepage;
        return this;
    }

    public Short getStatus() {
        return this.status;
    }

    public MenuPjo setStatus(Short status) {
        this.status = status;
        return this;
    }

    public BigDecimal getCreateBy() {
        return this.createBy;
    }

    public MenuPjo setCreateBy(BigDecimal createBy) {
        this.createBy = createBy;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public MenuPjo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MenuPjo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(pageUrl);
        sb.append(", ").append(parentId);
        sb.append(", ").append(level);
        sb.append(", ").append(isHomepage);
        sb.append(", ").append(status);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
