/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 国债网点表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NationalDebtDotsCopy1Pjo implements Serializable {

    private static final long serialVersionUID = -61552215;

    private BigDecimal id;
    private String     dotRegion;
    private String     dotName;
    private BigDecimal orgId;
    private BigDecimal operatorId;
    private Timestamp  operatingTime;
    private BigDecimal dotCode;
    private Integer    state;
    private String     address;

    public NationalDebtDotsCopy1Pjo() {}

    public NationalDebtDotsCopy1Pjo(NationalDebtDotsCopy1Pjo value) {
        this.id = value.id;
        this.dotRegion = value.dotRegion;
        this.dotName = value.dotName;
        this.orgId = value.orgId;
        this.operatorId = value.operatorId;
        this.operatingTime = value.operatingTime;
        this.dotCode = value.dotCode;
        this.state = value.state;
        this.address = value.address;
    }

    public NationalDebtDotsCopy1Pjo(
        BigDecimal id,
        String     dotRegion,
        String     dotName,
        BigDecimal orgId,
        BigDecimal operatorId,
        Timestamp  operatingTime,
        BigDecimal dotCode,
        Integer    state,
        String     address
    ) {
        this.id = id;
        this.dotRegion = dotRegion;
        this.dotName = dotName;
        this.orgId = orgId;
        this.operatorId = operatorId;
        this.operatingTime = operatingTime;
        this.dotCode = dotCode;
        this.state = state;
        this.address = address;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public NationalDebtDotsCopy1Pjo setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    public String getDotRegion() {
        return this.dotRegion;
    }

    public NationalDebtDotsCopy1Pjo setDotRegion(String dotRegion) {
        this.dotRegion = dotRegion;
        return this;
    }

    public String getDotName() {
        return this.dotName;
    }

    public NationalDebtDotsCopy1Pjo setDotName(String dotName) {
        this.dotName = dotName;
        return this;
    }

    public BigDecimal getOrgId() {
        return this.orgId;
    }

    public NationalDebtDotsCopy1Pjo setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
        return this;
    }

    public BigDecimal getOperatorId() {
        return this.operatorId;
    }

    public NationalDebtDotsCopy1Pjo setOperatorId(BigDecimal operatorId) {
        this.operatorId = operatorId;
        return this;
    }

    public Timestamp getOperatingTime() {
        return this.operatingTime;
    }

    public NationalDebtDotsCopy1Pjo setOperatingTime(Timestamp operatingTime) {
        this.operatingTime = operatingTime;
        return this;
    }

    public BigDecimal getDotCode() {
        return this.dotCode;
    }

    public NationalDebtDotsCopy1Pjo setDotCode(BigDecimal dotCode) {
        this.dotCode = dotCode;
        return this;
    }

    public Integer getState() {
        return this.state;
    }

    public NationalDebtDotsCopy1Pjo setState(Integer state) {
        this.state = state;
        return this;
    }

    public String getAddress() {
        return this.address;
    }

    public NationalDebtDotsCopy1Pjo setAddress(String address) {
        this.address = address;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NationalDebtDotsCopy1Pjo (");

        sb.append(id);
        sb.append(", ").append(dotRegion);
        sb.append(", ").append(dotName);
        sb.append(", ").append(orgId);
        sb.append(", ").append(operatorId);
        sb.append(", ").append(operatingTime);
        sb.append(", ").append(dotCode);
        sb.append(", ").append(state);
        sb.append(", ").append(address);

        sb.append(")");
        return sb.toString();
    }
}
