/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * 政策服务
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyServicePjo implements Serializable {

    private static final long serialVersionUID = -1297305880;

    private BigDecimal   id;
    private String       name;
    private Integer      type;
    private BigDecimal   orgId;
    private String       keyWords;
    private String       acceptOrgName;
    private BigDecimal[] acceptDivisionIds;
    private String[]     acceptDivisionNames;
    private String       feeScale;
    private Integer      priority;
    private Integer      status;
    private String       content;
    private Timestamp    acceptStartTime;
    private Timestamp    acceptEndTime;
    private BigDecimal   createUser;
    private BigDecimal   updateUser;
    private Timestamp    createTime;
    private Timestamp    updateTime;
    private Integer      acceptType;
    private BigDecimal   acceptOrgId;

    public PolicyServicePjo() {}

    public PolicyServicePjo(PolicyServicePjo value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.orgId = value.orgId;
        this.keyWords = value.keyWords;
        this.acceptOrgName = value.acceptOrgName;
        this.acceptDivisionIds = value.acceptDivisionIds;
        this.acceptDivisionNames = value.acceptDivisionNames;
        this.feeScale = value.feeScale;
        this.priority = value.priority;
        this.status = value.status;
        this.content = value.content;
        this.acceptStartTime = value.acceptStartTime;
        this.acceptEndTime = value.acceptEndTime;
        this.createUser = value.createUser;
        this.updateUser = value.updateUser;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.acceptType = value.acceptType;
        this.acceptOrgId = value.acceptOrgId;
    }

    public PolicyServicePjo(
        BigDecimal   id,
        String       name,
        Integer      type,
        BigDecimal   orgId,
        String       keyWords,
        String       acceptOrgName,
        BigDecimal[] acceptDivisionIds,
        String[]     acceptDivisionNames,
        String       feeScale,
        Integer      priority,
        Integer      status,
        String       content,
        Timestamp    acceptStartTime,
        Timestamp    acceptEndTime,
        BigDecimal   createUser,
        BigDecimal   updateUser,
        Timestamp    createTime,
        Timestamp    updateTime,
        Integer      acceptType,
        BigDecimal   acceptOrgId
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.orgId = orgId;
        this.keyWords = keyWords;
        this.acceptOrgName = acceptOrgName;
        this.acceptDivisionIds = acceptDivisionIds;
        this.acceptDivisionNames = acceptDivisionNames;
        this.feeScale = feeScale;
        this.priority = priority;
        this.status = status;
        this.content = content;
        this.acceptStartTime = acceptStartTime;
        this.acceptEndTime = acceptEndTime;
        this.createUser = createUser;
        this.updateUser = updateUser;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.acceptType = acceptType;
        this.acceptOrgId = acceptOrgId;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public PolicyServicePjo setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public PolicyServicePjo setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getType() {
        return this.type;
    }

    public PolicyServicePjo setType(Integer type) {
        this.type = type;
        return this;
    }

    public BigDecimal getOrgId() {
        return this.orgId;
    }

    public PolicyServicePjo setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
        return this;
    }

    public String getKeyWords() {
        return this.keyWords;
    }

    public PolicyServicePjo setKeyWords(String keyWords) {
        this.keyWords = keyWords;
        return this;
    }

    public String getAcceptOrgName() {
        return this.acceptOrgName;
    }

    public PolicyServicePjo setAcceptOrgName(String acceptOrgName) {
        this.acceptOrgName = acceptOrgName;
        return this;
    }

    public BigDecimal[] getAcceptDivisionIds() {
        return this.acceptDivisionIds;
    }

    public PolicyServicePjo setAcceptDivisionIds(BigDecimal... acceptDivisionIds) {
        this.acceptDivisionIds = acceptDivisionIds;
        return this;
    }

    public String[] getAcceptDivisionNames() {
        return this.acceptDivisionNames;
    }

    public PolicyServicePjo setAcceptDivisionNames(String... acceptDivisionNames) {
        this.acceptDivisionNames = acceptDivisionNames;
        return this;
    }

    public String getFeeScale() {
        return this.feeScale;
    }

    public PolicyServicePjo setFeeScale(String feeScale) {
        this.feeScale = feeScale;
        return this;
    }

    public Integer getPriority() {
        return this.priority;
    }

    public PolicyServicePjo setPriority(Integer priority) {
        this.priority = priority;
        return this;
    }

    public Integer getStatus() {
        return this.status;
    }

    public PolicyServicePjo setStatus(Integer status) {
        this.status = status;
        return this;
    }

    public String getContent() {
        return this.content;
    }

    public PolicyServicePjo setContent(String content) {
        this.content = content;
        return this;
    }

    public Timestamp getAcceptStartTime() {
        return this.acceptStartTime;
    }

    public PolicyServicePjo setAcceptStartTime(Timestamp acceptStartTime) {
        this.acceptStartTime = acceptStartTime;
        return this;
    }

    public Timestamp getAcceptEndTime() {
        return this.acceptEndTime;
    }

    public PolicyServicePjo setAcceptEndTime(Timestamp acceptEndTime) {
        this.acceptEndTime = acceptEndTime;
        return this;
    }

    public BigDecimal getCreateUser() {
        return this.createUser;
    }

    public PolicyServicePjo setCreateUser(BigDecimal createUser) {
        this.createUser = createUser;
        return this;
    }

    public BigDecimal getUpdateUser() {
        return this.updateUser;
    }

    public PolicyServicePjo setUpdateUser(BigDecimal updateUser) {
        this.updateUser = updateUser;
        return this;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public PolicyServicePjo setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
        return this;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public PolicyServicePjo setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    public Integer getAcceptType() {
        return this.acceptType;
    }

    public PolicyServicePjo setAcceptType(Integer acceptType) {
        this.acceptType = acceptType;
        return this;
    }

    public BigDecimal getAcceptOrgId() {
        return this.acceptOrgId;
    }

    public PolicyServicePjo setAcceptOrgId(BigDecimal acceptOrgId) {
        this.acceptOrgId = acceptOrgId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PolicyServicePjo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(orgId);
        sb.append(", ").append(keyWords);
        sb.append(", ").append(acceptOrgName);
        sb.append(", ").append(Arrays.toString(acceptDivisionIds));
        sb.append(", ").append(Arrays.toString(acceptDivisionNames));
        sb.append(", ").append(feeScale);
        sb.append(", ").append(priority);
        sb.append(", ").append(status);
        sb.append(", ").append(content);
        sb.append(", ").append(acceptStartTime);
        sb.append(", ").append(acceptEndTime);
        sb.append(", ").append(createUser);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(acceptType);
        sb.append(", ").append(acceptOrgId);

        sb.append(")");
        return sb.toString();
    }
}
