/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 风险分担申请处理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RiskshareApplyProcessPjo implements Serializable {

    private static final long serialVersionUID = -2060759382;

    private BigDecimal id;
    private BigDecimal riskshareApplyId;
    private BigDecimal handlerId;
    private String     handlerName;
    private BigDecimal amount;
    private String     msg;
    private String     handlerFiles;
    private Integer    state;
    private BigDecimal createUser;
    private Timestamp  createTime;
    private Short      status;

    public RiskshareApplyProcessPjo() {}

    public RiskshareApplyProcessPjo(RiskshareApplyProcessPjo value) {
        this.id = value.id;
        this.riskshareApplyId = value.riskshareApplyId;
        this.handlerId = value.handlerId;
        this.handlerName = value.handlerName;
        this.amount = value.amount;
        this.msg = value.msg;
        this.handlerFiles = value.handlerFiles;
        this.state = value.state;
        this.createUser = value.createUser;
        this.createTime = value.createTime;
        this.status = value.status;
    }

    public RiskshareApplyProcessPjo(
        BigDecimal id,
        BigDecimal riskshareApplyId,
        BigDecimal handlerId,
        String     handlerName,
        BigDecimal amount,
        String     msg,
        String     handlerFiles,
        Integer    state,
        BigDecimal createUser,
        Timestamp  createTime,
        Short      status
    ) {
        this.id = id;
        this.riskshareApplyId = riskshareApplyId;
        this.handlerId = handlerId;
        this.handlerName = handlerName;
        this.amount = amount;
        this.msg = msg;
        this.handlerFiles = handlerFiles;
        this.state = state;
        this.createUser = createUser;
        this.createTime = createTime;
        this.status = status;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public RiskshareApplyProcessPjo setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    public BigDecimal getRiskshareApplyId() {
        return this.riskshareApplyId;
    }

    public RiskshareApplyProcessPjo setRiskshareApplyId(BigDecimal riskshareApplyId) {
        this.riskshareApplyId = riskshareApplyId;
        return this;
    }

    public BigDecimal getHandlerId() {
        return this.handlerId;
    }

    public RiskshareApplyProcessPjo setHandlerId(BigDecimal handlerId) {
        this.handlerId = handlerId;
        return this;
    }

    public String getHandlerName() {
        return this.handlerName;
    }

    public RiskshareApplyProcessPjo setHandlerName(String handlerName) {
        this.handlerName = handlerName;
        return this;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public RiskshareApplyProcessPjo setAmount(BigDecimal amount) {
        this.amount = amount;
        return this;
    }

    public String getMsg() {
        return this.msg;
    }

    public RiskshareApplyProcessPjo setMsg(String msg) {
        this.msg = msg;
        return this;
    }

    public String getHandlerFiles() {
        return this.handlerFiles;
    }

    public RiskshareApplyProcessPjo setHandlerFiles(String handlerFiles) {
        this.handlerFiles = handlerFiles;
        return this;
    }

    public Integer getState() {
        return this.state;
    }

    public RiskshareApplyProcessPjo setState(Integer state) {
        this.state = state;
        return this;
    }

    public BigDecimal getCreateUser() {
        return this.createUser;
    }

    public RiskshareApplyProcessPjo setCreateUser(BigDecimal createUser) {
        this.createUser = createUser;
        return this;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public RiskshareApplyProcessPjo setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
        return this;
    }

    public Short getStatus() {
        return this.status;
    }

    public RiskshareApplyProcessPjo setStatus(Short status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RiskshareApplyProcessPjo (");

        sb.append(id);
        sb.append(", ").append(riskshareApplyId);
        sb.append(", ").append(handlerId);
        sb.append(", ").append(handlerName);
        sb.append(", ").append(amount);
        sb.append(", ").append(msg);
        sb.append(", ").append(handlerFiles);
        sb.append(", ").append(state);
        sb.append(", ").append(createUser);
        sb.append(", ").append(createTime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
