/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * 商品系统表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopWarePjo implements Serializable {

    private static final long serialVersionUID = 545248471;

    private BigDecimal id;
    private String     wareName;
    private Integer    warePrice;
    private Integer    wareStock;
    private Integer    wareSold;
    private Short      isDiscount;
    private Integer    discountLvl;
    private Short      isPromotion;
    private Integer    promotionNum;
    private String     wareDes;
    private String     wareInfo;
    private Short      status;
    private Short      isDel;
    private BigDecimal createBy;
    private Timestamp  createAt;
    private BigDecimal updateBy;
    private Timestamp  updateAt;
    private Integer    wareScore;
    private BigDecimal coverImgId;
    private String[]   infoImgIds;

    public ShopWarePjo() {}

    public ShopWarePjo(ShopWarePjo value) {
        this.id = value.id;
        this.wareName = value.wareName;
        this.warePrice = value.warePrice;
        this.wareStock = value.wareStock;
        this.wareSold = value.wareSold;
        this.isDiscount = value.isDiscount;
        this.discountLvl = value.discountLvl;
        this.isPromotion = value.isPromotion;
        this.promotionNum = value.promotionNum;
        this.wareDes = value.wareDes;
        this.wareInfo = value.wareInfo;
        this.status = value.status;
        this.isDel = value.isDel;
        this.createBy = value.createBy;
        this.createAt = value.createAt;
        this.updateBy = value.updateBy;
        this.updateAt = value.updateAt;
        this.wareScore = value.wareScore;
        this.coverImgId = value.coverImgId;
        this.infoImgIds = value.infoImgIds;
    }

    public ShopWarePjo(
        BigDecimal id,
        String     wareName,
        Integer    warePrice,
        Integer    wareStock,
        Integer    wareSold,
        Short      isDiscount,
        Integer    discountLvl,
        Short      isPromotion,
        Integer    promotionNum,
        String     wareDes,
        String     wareInfo,
        Short      status,
        Short      isDel,
        BigDecimal createBy,
        Timestamp  createAt,
        BigDecimal updateBy,
        Timestamp  updateAt,
        Integer    wareScore,
        BigDecimal coverImgId,
        String[]   infoImgIds
    ) {
        this.id = id;
        this.wareName = wareName;
        this.warePrice = warePrice;
        this.wareStock = wareStock;
        this.wareSold = wareSold;
        this.isDiscount = isDiscount;
        this.discountLvl = discountLvl;
        this.isPromotion = isPromotion;
        this.promotionNum = promotionNum;
        this.wareDes = wareDes;
        this.wareInfo = wareInfo;
        this.status = status;
        this.isDel = isDel;
        this.createBy = createBy;
        this.createAt = createAt;
        this.updateBy = updateBy;
        this.updateAt = updateAt;
        this.wareScore = wareScore;
        this.coverImgId = coverImgId;
        this.infoImgIds = infoImgIds;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public ShopWarePjo setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    public String getWareName() {
        return this.wareName;
    }

    public ShopWarePjo setWareName(String wareName) {
        this.wareName = wareName;
        return this;
    }

    public Integer getWarePrice() {
        return this.warePrice;
    }

    public ShopWarePjo setWarePrice(Integer warePrice) {
        this.warePrice = warePrice;
        return this;
    }

    public Integer getWareStock() {
        return this.wareStock;
    }

    public ShopWarePjo setWareStock(Integer wareStock) {
        this.wareStock = wareStock;
        return this;
    }

    public Integer getWareSold() {
        return this.wareSold;
    }

    public ShopWarePjo setWareSold(Integer wareSold) {
        this.wareSold = wareSold;
        return this;
    }

    public Short getIsDiscount() {
        return this.isDiscount;
    }

    public ShopWarePjo setIsDiscount(Short isDiscount) {
        this.isDiscount = isDiscount;
        return this;
    }

    public Integer getDiscountLvl() {
        return this.discountLvl;
    }

    public ShopWarePjo setDiscountLvl(Integer discountLvl) {
        this.discountLvl = discountLvl;
        return this;
    }

    public Short getIsPromotion() {
        return this.isPromotion;
    }

    public ShopWarePjo setIsPromotion(Short isPromotion) {
        this.isPromotion = isPromotion;
        return this;
    }

    public Integer getPromotionNum() {
        return this.promotionNum;
    }

    public ShopWarePjo setPromotionNum(Integer promotionNum) {
        this.promotionNum = promotionNum;
        return this;
    }

    public String getWareDes() {
        return this.wareDes;
    }

    public ShopWarePjo setWareDes(String wareDes) {
        this.wareDes = wareDes;
        return this;
    }

    public String getWareInfo() {
        return this.wareInfo;
    }

    public ShopWarePjo setWareInfo(String wareInfo) {
        this.wareInfo = wareInfo;
        return this;
    }

    public Short getStatus() {
        return this.status;
    }

    public ShopWarePjo setStatus(Short status) {
        this.status = status;
        return this;
    }

    public Short getIsDel() {
        return this.isDel;
    }

    public ShopWarePjo setIsDel(Short isDel) {
        this.isDel = isDel;
        return this;
    }

    public BigDecimal getCreateBy() {
        return this.createBy;
    }

    public ShopWarePjo setCreateBy(BigDecimal createBy) {
        this.createBy = createBy;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public ShopWarePjo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public BigDecimal getUpdateBy() {
        return this.updateBy;
    }

    public ShopWarePjo setUpdateBy(BigDecimal updateBy) {
        this.updateBy = updateBy;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public ShopWarePjo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public Integer getWareScore() {
        return this.wareScore;
    }

    public ShopWarePjo setWareScore(Integer wareScore) {
        this.wareScore = wareScore;
        return this;
    }

    public BigDecimal getCoverImgId() {
        return this.coverImgId;
    }

    public ShopWarePjo setCoverImgId(BigDecimal coverImgId) {
        this.coverImgId = coverImgId;
        return this;
    }

    public String[] getInfoImgIds() {
        return this.infoImgIds;
    }

    public ShopWarePjo setInfoImgIds(String... infoImgIds) {
        this.infoImgIds = infoImgIds;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShopWarePjo (");

        sb.append(id);
        sb.append(", ").append(wareName);
        sb.append(", ").append(warePrice);
        sb.append(", ").append(wareStock);
        sb.append(", ").append(wareSold);
        sb.append(", ").append(isDiscount);
        sb.append(", ").append(discountLvl);
        sb.append(", ").append(isPromotion);
        sb.append(", ").append(promotionNum);
        sb.append(", ").append(wareDes);
        sb.append(", ").append(wareInfo);
        sb.append(", ").append(status);
        sb.append(", ").append(isDel);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(wareScore);
        sb.append(", ").append(coverImgId);
        sb.append(", ").append(Arrays.toString(infoImgIds));

        sb.append(")");
        return sb.toString();
    }
}
