/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * 项目大类型
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TermBasePjo implements Serializable {

    private static final long serialVersionUID = -1972847231;

    private BigDecimal id;
    private BigDecimal termTypeCode;
    private String     termTypeName;
    private BigDecimal parentCode;
    private Short      level;
    private BigDecimal discountScale;

    public TermBasePjo() {}

    public TermBasePjo(TermBasePjo value) {
        this.id = value.id;
        this.termTypeCode = value.termTypeCode;
        this.termTypeName = value.termTypeName;
        this.parentCode = value.parentCode;
        this.level = value.level;
        this.discountScale = value.discountScale;
    }

    public TermBasePjo(
        BigDecimal id,
        BigDecimal termTypeCode,
        String     termTypeName,
        BigDecimal parentCode,
        Short      level,
        BigDecimal discountScale
    ) {
        this.id = id;
        this.termTypeCode = termTypeCode;
        this.termTypeName = termTypeName;
        this.parentCode = parentCode;
        this.level = level;
        this.discountScale = discountScale;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public TermBasePjo setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    public BigDecimal getTermTypeCode() {
        return this.termTypeCode;
    }

    public TermBasePjo setTermTypeCode(BigDecimal termTypeCode) {
        this.termTypeCode = termTypeCode;
        return this;
    }

    public String getTermTypeName() {
        return this.termTypeName;
    }

    public TermBasePjo setTermTypeName(String termTypeName) {
        this.termTypeName = termTypeName;
        return this;
    }

    public BigDecimal getParentCode() {
        return this.parentCode;
    }

    public TermBasePjo setParentCode(BigDecimal parentCode) {
        this.parentCode = parentCode;
        return this;
    }

    public Short getLevel() {
        return this.level;
    }

    public TermBasePjo setLevel(Short level) {
        this.level = level;
        return this;
    }

    public BigDecimal getDiscountScale() {
        return this.discountScale;
    }

    public TermBasePjo setDiscountScale(BigDecimal discountScale) {
        this.discountScale = discountScale;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TermBasePjo (");

        sb.append(id);
        sb.append(", ").append(termTypeCode);
        sb.append(", ").append(termTypeName);
        sb.append(", ").append(parentCode);
        sb.append(", ").append(level);
        sb.append(", ").append(discountScale);

        sb.append(")");
        return sb.toString();
    }
}
