/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 村站采集的公司贷款信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VillageCompanyLoanPjo implements Serializable {

    private static final long serialVersionUID = 1215330906;

    private BigDecimal id;
    private BigDecimal villageCompanyInfoId;
    private String     loanOrgName;
    private BigDecimal loanBalance;
    private Timestamp  loanStartDate;
    private Timestamp  loanEndDate;
    private String     loanMortgage;
    private BigDecimal loanRate;
    private Short      status;
    private BigDecimal createUser;
    private Timestamp  createTime;
    private BigDecimal updateUser;
    private Timestamp  updateTime;

    public VillageCompanyLoanPjo() {}

    public VillageCompanyLoanPjo(VillageCompanyLoanPjo value) {
        this.id = value.id;
        this.villageCompanyInfoId = value.villageCompanyInfoId;
        this.loanOrgName = value.loanOrgName;
        this.loanBalance = value.loanBalance;
        this.loanStartDate = value.loanStartDate;
        this.loanEndDate = value.loanEndDate;
        this.loanMortgage = value.loanMortgage;
        this.loanRate = value.loanRate;
        this.status = value.status;
        this.createUser = value.createUser;
        this.createTime = value.createTime;
        this.updateUser = value.updateUser;
        this.updateTime = value.updateTime;
    }

    public VillageCompanyLoanPjo(
        BigDecimal id,
        BigDecimal villageCompanyInfoId,
        String     loanOrgName,
        BigDecimal loanBalance,
        Timestamp  loanStartDate,
        Timestamp  loanEndDate,
        String     loanMortgage,
        BigDecimal loanRate,
        Short      status,
        BigDecimal createUser,
        Timestamp  createTime,
        BigDecimal updateUser,
        Timestamp  updateTime
    ) {
        this.id = id;
        this.villageCompanyInfoId = villageCompanyInfoId;
        this.loanOrgName = loanOrgName;
        this.loanBalance = loanBalance;
        this.loanStartDate = loanStartDate;
        this.loanEndDate = loanEndDate;
        this.loanMortgage = loanMortgage;
        this.loanRate = loanRate;
        this.status = status;
        this.createUser = createUser;
        this.createTime = createTime;
        this.updateUser = updateUser;
        this.updateTime = updateTime;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public VillageCompanyLoanPjo setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    public BigDecimal getVillageCompanyInfoId() {
        return this.villageCompanyInfoId;
    }

    public VillageCompanyLoanPjo setVillageCompanyInfoId(BigDecimal villageCompanyInfoId) {
        this.villageCompanyInfoId = villageCompanyInfoId;
        return this;
    }

    public String getLoanOrgName() {
        return this.loanOrgName;
    }

    public VillageCompanyLoanPjo setLoanOrgName(String loanOrgName) {
        this.loanOrgName = loanOrgName;
        return this;
    }

    public BigDecimal getLoanBalance() {
        return this.loanBalance;
    }

    public VillageCompanyLoanPjo setLoanBalance(BigDecimal loanBalance) {
        this.loanBalance = loanBalance;
        return this;
    }

    public Timestamp getLoanStartDate() {
        return this.loanStartDate;
    }

    public VillageCompanyLoanPjo setLoanStartDate(Timestamp loanStartDate) {
        this.loanStartDate = loanStartDate;
        return this;
    }

    public Timestamp getLoanEndDate() {
        return this.loanEndDate;
    }

    public VillageCompanyLoanPjo setLoanEndDate(Timestamp loanEndDate) {
        this.loanEndDate = loanEndDate;
        return this;
    }

    public String getLoanMortgage() {
        return this.loanMortgage;
    }

    public VillageCompanyLoanPjo setLoanMortgage(String loanMortgage) {
        this.loanMortgage = loanMortgage;
        return this;
    }

    public BigDecimal getLoanRate() {
        return this.loanRate;
    }

    public VillageCompanyLoanPjo setLoanRate(BigDecimal loanRate) {
        this.loanRate = loanRate;
        return this;
    }

    public Short getStatus() {
        return this.status;
    }

    public VillageCompanyLoanPjo setStatus(Short status) {
        this.status = status;
        return this;
    }

    public BigDecimal getCreateUser() {
        return this.createUser;
    }

    public VillageCompanyLoanPjo setCreateUser(BigDecimal createUser) {
        this.createUser = createUser;
        return this;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public VillageCompanyLoanPjo setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
        return this;
    }

    public BigDecimal getUpdateUser() {
        return this.updateUser;
    }

    public VillageCompanyLoanPjo setUpdateUser(BigDecimal updateUser) {
        this.updateUser = updateUser;
        return this;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public VillageCompanyLoanPjo setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VillageCompanyLoanPjo (");

        sb.append(id);
        sb.append(", ").append(villageCompanyInfoId);
        sb.append(", ").append(loanOrgName);
        sb.append(", ").append(loanBalance);
        sb.append(", ").append(loanStartDate);
        sb.append(", ").append(loanEndDate);
        sb.append(", ").append(loanMortgage);
        sb.append(", ").append(loanRate);
        sb.append(", ").append(status);
        sb.append(", ").append(createUser);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
