
spring:
  datasource:
    url: jdbc:p6spy:postgresql://192.168.15.12:58083/ndt_pro?searchpath=ndt
    username: postgres
    password: incitedata
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: MyHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 180000
      maximum-pool-size: 10
  jooq:
    sql-dialect: postgres
  redis:
    host: 192.168.15.14
    password:
    port: 6379
    database: 15
    jedis:
      pool:
        max-active: -1
        min-idle: 1
        max-wait: 1000s
        max-idle: 100
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  security:
    user:
      name: root
      password: 1234
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        scheduling: INFO
    com:
      zaxxer:
        hikari: INFO
server:
  port: 8787
