/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in ndt
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>ndt.act_evt_log_log_nr__seq</code>
     */
    public static final Sequence<Long> ACT_EVT_LOG_LOG_NR__SEQ = new SequenceImpl<Long>("act_evt_log_log_nr__seq", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.seq1</code>
     */
    public static final Sequence<Long> SEQ1 = new SequenceImpl<Long>("seq1", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.tb_farm0_copy_date</code>
     */
    public static final Sequence<Long> TB_FARM0_COPY_DATE = new SequenceImpl<Long>("tb_farm0_copy_date", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.tb_info_copy_date</code>
     */
    public static final Sequence<Long> TB_INFO_COPY_DATE = new SequenceImpl<Long>("tb_info_copy_date", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.tb_loan_done_record_seq</code>
     */
    public static final Sequence<Long> TB_LOAN_DONE_RECORD_SEQ = new SequenceImpl<Long>("tb_loan_done_record_seq", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.tb_major_seq</code>
     */
    public static final Sequence<Long> TB_MAJOR_SEQ = new SequenceImpl<Long>("tb_major_seq", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.tb_user_detail_id_seq</code>
     */
    public static final Sequence<Long> TB_USER_DETAIL_ID_SEQ = new SequenceImpl<Long>("tb_user_detail_id_seq", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.t_risks_share_id_seq</code>
     */
    public static final Sequence<Long> T_RISKS_SHARE_ID_SEQ = new SequenceImpl<Long>("t_risks_share_id_seq", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>ndt.t_risks_share_trace_id_seq</code>
     */
    public static final Sequence<Long> T_RISKS_SHARE_TRACE_ID_SEQ = new SequenceImpl<Long>("t_risks_share_trace_id_seq", Ndt.NDT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
