/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TCompanyDetailRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 企业用户信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCompanyDetail extends TableImpl<TCompanyDetailRecord> {

    private static final long serialVersionUID = -2109331;

    /**
     * The reference instance of <code>ndt.t_company_detail</code>
     */
    public static final TCompanyDetail T_COMPANY_DETAIL = new TCompanyDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TCompanyDetailRecord> getRecordType() {
        return TCompanyDetailRecord.class;
    }

    /**
     * The column <code>ndt.t_company_detail.id</code>.
     */
    public final TableField<TCompanyDetailRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_company_detail.contact_id</code>. 联系人用户id
     */
    public final TableField<TCompanyDetailRecord, BigDecimal> CONTACT_ID = createField("contact_id", org.jooq.impl.SQLDataType.NUMERIC, this, "联系人用户id");

    /**
     * The column <code>ndt.t_company_detail.certificate_type</code>. 证件类型
     */
    public final TableField<TCompanyDetailRecord, Integer> CERTIFICATE_TYPE = createField("certificate_type", org.jooq.impl.SQLDataType.INTEGER, this, "证件类型");

    /**
     * The column <code>ndt.t_company_detail.name</code>. 企业名称
     */
    public final TableField<TCompanyDetailRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(60), this, "企业名称");

    /**
     * The column <code>ndt.t_company_detail.code</code>. 统一社会信用代码或注册号
     */
    public final TableField<TCompanyDetailRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(30), this, "统一社会信用代码或注册号");

    /**
     * The column <code>ndt.t_company_detail.address</code>. 注册地址
     */
    public final TableField<TCompanyDetailRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(100), this, "注册地址");

    /**
     * The column <code>ndt.t_company_detail.company_type</code>. 企业类型
     */
    public final TableField<TCompanyDetailRecord, Integer> COMPANY_TYPE = createField("company_type", org.jooq.impl.SQLDataType.INTEGER, this, "企业类型");

    /**
     * The column <code>ndt.t_company_detail.industry_type</code>. 所属行业
     */
    public final TableField<TCompanyDetailRecord, Integer> INDUSTRY_TYPE = createField("industry_type", org.jooq.impl.SQLDataType.INTEGER, this, "所属行业");

    /**
     * The column <code>ndt.t_company_detail.setup_time</code>. 成立时间
     */
    public final TableField<TCompanyDetailRecord, Timestamp> SETUP_TIME = createField("setup_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "成立时间");

    /**
     * The column <code>ndt.t_company_detail.business_scope</code>. 经营范围
     */
    public final TableField<TCompanyDetailRecord, String> BUSINESS_SCOPE = createField("business_scope", org.jooq.impl.SQLDataType.VARCHAR(200), this, "经营范围");

    /**
     * The column <code>ndt.t_company_detail.business_deadline</code>. 经营期限
     */
    public final TableField<TCompanyDetailRecord, Timestamp> BUSINESS_DEADLINE = createField("business_deadline", org.jooq.impl.SQLDataType.TIMESTAMP, this, "经营期限");

    /**
     * The column <code>ndt.t_company_detail.registered_capital</code>. 注册资本
     */
    public final TableField<TCompanyDetailRecord, String> REGISTERED_CAPITAL = createField("registered_capital", org.jooq.impl.SQLDataType.VARCHAR(20), this, "注册资本");

    /**
     * The column <code>ndt.t_company_detail.is_emerging</code>. 是否为新兴经营主体
     */
    public final TableField<TCompanyDetailRecord, Boolean> IS_EMERGING = createField("is_emerging", org.jooq.impl.SQLDataType.BOOLEAN, this, "是否为新兴经营主体");

    /**
     * The column <code>ndt.t_company_detail.legal_person</code>. 法人
     */
    public final TableField<TCompanyDetailRecord, String> LEGAL_PERSON = createField("legal_person", org.jooq.impl.SQLDataType.VARCHAR(40), this, "法人");

    /**
     * The column <code>ndt.t_company_detail.legal_person_identity_id</code>. 法人身份证
     */
    public final TableField<TCompanyDetailRecord, String> LEGAL_PERSON_IDENTITY_ID = createField("legal_person_identity_id", org.jooq.impl.SQLDataType.VARCHAR(40), this, "法人身份证");

    /**
     * The column <code>ndt.t_company_detail.legal_person_id_deadline</code>. 法人身份证截止时间
     */
    public final TableField<TCompanyDetailRecord, Timestamp> LEGAL_PERSON_ID_DEADLINE = createField("legal_person_id_deadline", org.jooq.impl.SQLDataType.TIMESTAMP, this, "法人身份证截止时间");

    /**
     * The column <code>ndt.t_company_detail.related_img_urls</code>. 相关照片
     */
    public final TableField<TCompanyDetailRecord, String> RELATED_IMG_URLS = createField("related_img_urls", org.jooq.impl.SQLDataType.VARCHAR(300), this, "相关照片");

    /**
     * The column <code>ndt.t_company_detail.status</code>. 记录状态
     */
    public final TableField<TCompanyDetailRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "记录状态");

    /**
     * The column <code>ndt.t_company_detail.update_by</code>. 更新人
     */
    public final TableField<TCompanyDetailRecord, BigDecimal> UPDATE_BY = createField("update_by", org.jooq.impl.SQLDataType.NUMERIC, this, "更新人");

    /**
     * The column <code>ndt.t_company_detail.update_at</code>. 更新时间
     */
    public final TableField<TCompanyDetailRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>ndt.t_company_detail.contact_name</code>. 联系人姓名
     */
    public final TableField<TCompanyDetailRecord, String> CONTACT_NAME = createField("contact_name", org.jooq.impl.SQLDataType.VARCHAR(30), this, "联系人姓名");

    /**
     * The column <code>ndt.t_company_detail.contact_identity_id</code>. 联系人身份证
     */
    public final TableField<TCompanyDetailRecord, String> CONTACT_IDENTITY_ID = createField("contact_identity_id", org.jooq.impl.SQLDataType.VARCHAR(30), this, "联系人身份证");

    /**
     * The column <code>ndt.t_company_detail.division_id</code>. 企业注册地址
     */
    public final TableField<TCompanyDetailRecord, BigDecimal> DIVISION_ID = createField("division_id", org.jooq.impl.SQLDataType.NUMERIC, this, "企业注册地址");

    /**
     * Create a <code>ndt.t_company_detail</code> table reference
     */
    public TCompanyDetail() {
        this(DSL.name("t_company_detail"), null);
    }

    /**
     * Create an aliased <code>ndt.t_company_detail</code> table reference
     */
    public TCompanyDetail(String alias) {
        this(DSL.name(alias), T_COMPANY_DETAIL);
    }

    /**
     * Create an aliased <code>ndt.t_company_detail</code> table reference
     */
    public TCompanyDetail(Name alias) {
        this(alias, T_COMPANY_DETAIL);
    }

    private TCompanyDetail(Name alias, Table<TCompanyDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private TCompanyDetail(Name alias, Table<TCompanyDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "企业用户信息表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_COMPANY_DETAIL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TCompanyDetailRecord> getPrimaryKey() {
        return Keys.T_COMPANY_DETAIL_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TCompanyDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<TCompanyDetailRecord>>asList(Keys.T_COMPANY_DETAIL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCompanyDetail as(String alias) {
        return new TCompanyDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCompanyDetail as(Name alias) {
        return new TCompanyDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TCompanyDetail rename(String name) {
        return new TCompanyDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TCompanyDetail rename(Name name) {
        return new TCompanyDetail(name, null);
    }
}
