/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TNationalDebtDotsRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 国债网点表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TNationalDebtDots extends TableImpl<TNationalDebtDotsRecord> {

    private static final long serialVersionUID = -1392505948;

    /**
     * The reference instance of <code>ndt.t_national_debt_dots</code>
     */
    public static final TNationalDebtDots T_NATIONAL_DEBT_DOTS = new TNationalDebtDots();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TNationalDebtDotsRecord> getRecordType() {
        return TNationalDebtDotsRecord.class;
    }

    /**
     * The column <code>ndt.t_national_debt_dots.id</code>.
     */
    public final TableField<TNationalDebtDotsRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_national_debt_dots.dot_region</code>. 网点所在区域编码
     */
    public final TableField<TNationalDebtDotsRecord, String> DOT_REGION = createField("dot_region", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "网点所在区域编码");

    /**
     * The column <code>ndt.t_national_debt_dots.dot_name</code>. 网点名称
     */
    public final TableField<TNationalDebtDotsRecord, String> DOT_NAME = createField("dot_name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "网点名称");

    /**
     * The column <code>ndt.t_national_debt_dots.org_id</code>. 机构ID
     */
    public final TableField<TNationalDebtDotsRecord, BigDecimal> ORG_ID = createField("org_id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "机构ID");

    /**
     * The column <code>ndt.t_national_debt_dots.operator_id</code>. 操作者ID
     */
    public final TableField<TNationalDebtDotsRecord, BigDecimal> OPERATOR_ID = createField("operator_id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "操作者ID");

    /**
     * The column <code>ndt.t_national_debt_dots.operating_time</code>. 操作日期
     */
    public final TableField<TNationalDebtDotsRecord, Timestamp> OPERATING_TIME = createField("operating_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "操作日期");

    /**
     * The column <code>ndt.t_national_debt_dots.dot_code</code>. 网点编码
     */
    public final TableField<TNationalDebtDotsRecord, BigDecimal> DOT_CODE = createField("dot_code", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "网点编码");

    /**
     * The column <code>ndt.t_national_debt_dots.state</code>. 网点状态：0禁用，1启用
     */
    public final TableField<TNationalDebtDotsRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "网点状态：0禁用，1启用");

    /**
     * The column <code>ndt.t_national_debt_dots.address</code>. 网点地址
     */
    public final TableField<TNationalDebtDotsRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "网点地址");

    /**
     * Create a <code>ndt.t_national_debt_dots</code> table reference
     */
    public TNationalDebtDots() {
        this(DSL.name("t_national_debt_dots"), null);
    }

    /**
     * Create an aliased <code>ndt.t_national_debt_dots</code> table reference
     */
    public TNationalDebtDots(String alias) {
        this(DSL.name(alias), T_NATIONAL_DEBT_DOTS);
    }

    /**
     * Create an aliased <code>ndt.t_national_debt_dots</code> table reference
     */
    public TNationalDebtDots(Name alias) {
        this(alias, T_NATIONAL_DEBT_DOTS);
    }

    private TNationalDebtDots(Name alias, Table<TNationalDebtDotsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TNationalDebtDots(Name alias, Table<TNationalDebtDotsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "国债网点表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_NATIONAL_DEBT_DOTS_DOT_REGION_DOT_NAME_KEY, Indexes.T_NATIONAL_DEBT_DOTS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TNationalDebtDotsRecord> getPrimaryKey() {
        return Keys.T_NATIONAL_DEBT_DOTS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TNationalDebtDotsRecord>> getKeys() {
        return Arrays.<UniqueKey<TNationalDebtDotsRecord>>asList(Keys.T_NATIONAL_DEBT_DOTS_PKEY, Keys.T_NATIONAL_DEBT_DOTS_DOT_REGION_DOT_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TNationalDebtDots as(String alias) {
        return new TNationalDebtDots(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TNationalDebtDots as(Name alias) {
        return new TNationalDebtDots(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TNationalDebtDots rename(String name) {
        return new TNationalDebtDots(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TNationalDebtDots rename(Name name) {
        return new TNationalDebtDots(name, null);
    }
}
