/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TVillageCompanyManagementRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 村站采集的公司经营状况表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillageCompanyManagement extends TableImpl<TVillageCompanyManagementRecord> {

    private static final long serialVersionUID = -682503881;

    /**
     * The reference instance of <code>ndt.t_village_company_management</code>
     */
    public static final TVillageCompanyManagement T_VILLAGE_COMPANY_MANAGEMENT = new TVillageCompanyManagement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVillageCompanyManagementRecord> getRecordType() {
        return TVillageCompanyManagementRecord.class;
    }

    /**
     * The column <code>ndt.t_village_company_management.id</code>.
     */
    public final TableField<TVillageCompanyManagementRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_village_company_management.village_company_detail_id</code>. 公司详情ID
     */
    public final TableField<TVillageCompanyManagementRecord, BigDecimal> VILLAGE_COMPANY_DETAIL_ID = createField("village_company_detail_id", org.jooq.impl.SQLDataType.NUMERIC, this, "公司详情ID");

    /**
     * The column <code>ndt.t_village_company_management.running_address</code>. 经营地址
     */
    public final TableField<TVillageCompanyManagementRecord, String> RUNNING_ADDRESS = createField("running_address", org.jooq.impl.SQLDataType.VARCHAR(100), this, "经营地址");

    /**
     * The column <code>ndt.t_village_company_management.calendar_year</code>. 年度
     */
    public final TableField<TVillageCompanyManagementRecord, String> CALENDAR_YEAR = createField("calendar_year", org.jooq.impl.SQLDataType.VARCHAR(30), this, "年度");

    /**
     * The column <code>ndt.t_village_company_management.social_security_amt</code>. 社保缴纳金额
     */
    public final TableField<TVillageCompanyManagementRecord, BigDecimal> SOCIAL_SECURITY_AMT = createField("social_security_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "社保缴纳金额");

    /**
     * The column <code>ndt.t_village_company_management.management_evaluation</code>. 经营评价
     */
    public final TableField<TVillageCompanyManagementRecord, String> MANAGEMENT_EVALUATION = createField("management_evaluation", org.jooq.impl.SQLDataType.VARCHAR(10), this, "经营评价");

    /**
     * The column <code>ndt.t_village_company_management.local_tax_evaluation</code>. 地税评价
     */
    public final TableField<TVillageCompanyManagementRecord, String> LOCAL_TAX_EVALUATION = createField("local_tax_evaluation", org.jooq.impl.SQLDataType.VARCHAR(10), this, "地税评价");

    /**
     * The column <code>ndt.t_village_company_management.national_tax_evaluation</code>. 国税评价
     */
    public final TableField<TVillageCompanyManagementRecord, String> NATIONAL_TAX_EVALUATION = createField("national_tax_evaluation", org.jooq.impl.SQLDataType.VARCHAR(10), this, "国税评价");

    /**
     * The column <code>ndt.t_village_company_management.court_black_list</code>. 是否在法院黑名单中
     */
    public final TableField<TVillageCompanyManagementRecord, Boolean> COURT_BLACK_LIST = createField("court_black_list", org.jooq.impl.SQLDataType.BOOLEAN, this, "是否在法院黑名单中");

    /**
     * The column <code>ndt.t_village_company_management.commerce_black_list</code>. 是否在工商黑名单中
     */
    public final TableField<TVillageCompanyManagementRecord, Boolean> COMMERCE_BLACK_LIST = createField("commerce_black_list", org.jooq.impl.SQLDataType.BOOLEAN, this, "是否在工商黑名单中");

    /**
     * The column <code>ndt.t_village_company_management.status</code>.
     */
    public final TableField<TVillageCompanyManagementRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>ndt.t_village_company_management.create_by</code>.
     */
    public final TableField<TVillageCompanyManagementRecord, BigDecimal> CREATE_BY = createField("create_by", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_management.create_at</code>.
     */
    public final TableField<TVillageCompanyManagementRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ndt.t_village_company_management.update_by</code>.
     */
    public final TableField<TVillageCompanyManagementRecord, BigDecimal> UPDATE_BY = createField("update_by", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_management.update_at</code>.
     */
    public final TableField<TVillageCompanyManagementRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>ndt.t_village_company_management</code> table reference
     */
    public TVillageCompanyManagement() {
        this(DSL.name("t_village_company_management"), null);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_management</code> table reference
     */
    public TVillageCompanyManagement(String alias) {
        this(DSL.name(alias), T_VILLAGE_COMPANY_MANAGEMENT);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_management</code> table reference
     */
    public TVillageCompanyManagement(Name alias) {
        this(alias, T_VILLAGE_COMPANY_MANAGEMENT);
    }

    private TVillageCompanyManagement(Name alias, Table<TVillageCompanyManagementRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVillageCompanyManagement(Name alias, Table<TVillageCompanyManagementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "村站采集的公司经营状况表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_VILLAGE_COMPANY_MANAGEMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TVillageCompanyManagementRecord> getPrimaryKey() {
        return Keys.T_VILLAGE_COMPANY_MANAGEMENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TVillageCompanyManagementRecord>> getKeys() {
        return Arrays.<UniqueKey<TVillageCompanyManagementRecord>>asList(Keys.T_VILLAGE_COMPANY_MANAGEMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyManagement as(String alias) {
        return new TVillageCompanyManagement(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyManagement as(Name alias) {
        return new TVillageCompanyManagement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanyManagement rename(String name) {
        return new TVillageCompanyManagement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanyManagement rename(Name name) {
        return new TVillageCompanyManagement(name, null);
    }
}
