/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TVillageCompanySubsidyRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 村站采集的公司政府补贴信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillageCompanySubsidy extends TableImpl<TVillageCompanySubsidyRecord> {

    private static final long serialVersionUID = 1166429396;

    /**
     * The reference instance of <code>ndt.t_village_company_subsidy</code>
     */
    public static final TVillageCompanySubsidy T_VILLAGE_COMPANY_SUBSIDY = new TVillageCompanySubsidy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVillageCompanySubsidyRecord> getRecordType() {
        return TVillageCompanySubsidyRecord.class;
    }

    /**
     * The column <code>ndt.t_village_company_subsidy.id</code>.
     */
    public final TableField<TVillageCompanySubsidyRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_village_company_subsidy.village_company_info_id</code>. 公司详情ID
     */
    public final TableField<TVillageCompanySubsidyRecord, BigDecimal> VILLAGE_COMPANY_INFO_ID = createField("village_company_info_id", org.jooq.impl.SQLDataType.NUMERIC, this, "公司详情ID");

    /**
     * The column <code>ndt.t_village_company_subsidy.subsidy_name</code>. 补贴名称
     */
    public final TableField<TVillageCompanySubsidyRecord, String> SUBSIDY_NAME = createField("subsidy_name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "补贴名称");

    /**
     * The column <code>ndt.t_village_company_subsidy.subsidy_type</code>. 补贴类型
     */
    public final TableField<TVillageCompanySubsidyRecord, String> SUBSIDY_TYPE = createField("subsidy_type", org.jooq.impl.SQLDataType.VARCHAR(100), this, "补贴类型");

    /**
     * The column <code>ndt.t_village_company_subsidy.subsidy_scale</code>. 补贴规模
     */
    public final TableField<TVillageCompanySubsidyRecord, String> SUBSIDY_SCALE = createField("subsidy_scale", org.jooq.impl.SQLDataType.VARCHAR(50), this, "补贴规模");

    /**
     * The column <code>ndt.t_village_company_subsidy.subsidy_scale_unit</code>. 补贴规模单位
     */
    public final TableField<TVillageCompanySubsidyRecord, String> SUBSIDY_SCALE_UNIT = createField("subsidy_scale_unit", org.jooq.impl.SQLDataType.VARCHAR(50), this, "补贴规模单位");

    /**
     * The column <code>ndt.t_village_company_subsidy.grant_department</code>. 发放部门
     */
    public final TableField<TVillageCompanySubsidyRecord, String> GRANT_DEPARTMENT = createField("grant_department", org.jooq.impl.SQLDataType.VARCHAR(100), this, "发放部门");

    /**
     * The column <code>ndt.t_village_company_subsidy.subsidy_amount</code>. 补贴金额（万元）
     */
    public final TableField<TVillageCompanySubsidyRecord, BigDecimal> SUBSIDY_AMOUNT = createField("subsidy_amount", org.jooq.impl.SQLDataType.NUMERIC, this, "补贴金额（万元）");

    /**
     * The column <code>ndt.t_village_company_subsidy.subsidy_date</code>. 获得补贴时间
     */
    public final TableField<TVillageCompanySubsidyRecord, Timestamp> SUBSIDY_DATE = createField("subsidy_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "获得补贴时间");

    /**
     * The column <code>ndt.t_village_company_subsidy.subsidy_img</code>. 补贴凭证
     */
    public final TableField<TVillageCompanySubsidyRecord, BigDecimal[]> SUBSIDY_IMG = createField("subsidy_img", org.jooq.impl.SQLDataType.NUMERIC.getArrayDataType(), this, "补贴凭证");

    /**
     * The column <code>ndt.t_village_company_subsidy.status</code>.
     */
    public final TableField<TVillageCompanySubsidyRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>ndt.t_village_company_subsidy.create_user</code>.
     */
    public final TableField<TVillageCompanySubsidyRecord, BigDecimal> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_subsidy.create_time</code>.
     */
    public final TableField<TVillageCompanySubsidyRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ndt.t_village_company_subsidy.update_user</code>.
     */
    public final TableField<TVillageCompanySubsidyRecord, BigDecimal> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_subsidy.update_time</code>.
     */
    public final TableField<TVillageCompanySubsidyRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>ndt.t_village_company_subsidy</code> table reference
     */
    public TVillageCompanySubsidy() {
        this(DSL.name("t_village_company_subsidy"), null);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_subsidy</code> table reference
     */
    public TVillageCompanySubsidy(String alias) {
        this(DSL.name(alias), T_VILLAGE_COMPANY_SUBSIDY);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_subsidy</code> table reference
     */
    public TVillageCompanySubsidy(Name alias) {
        this(alias, T_VILLAGE_COMPANY_SUBSIDY);
    }

    private TVillageCompanySubsidy(Name alias, Table<TVillageCompanySubsidyRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVillageCompanySubsidy(Name alias, Table<TVillageCompanySubsidyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "村站采集的公司政府补贴信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_VILLAGE_COMPANY_SUBSIDY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TVillageCompanySubsidyRecord> getPrimaryKey() {
        return Keys.T_VILLAGE_COMPANY_SUBSIDY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TVillageCompanySubsidyRecord>> getKeys() {
        return Arrays.<UniqueKey<TVillageCompanySubsidyRecord>>asList(Keys.T_VILLAGE_COMPANY_SUBSIDY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanySubsidy as(String alias) {
        return new TVillageCompanySubsidy(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanySubsidy as(Name alias) {
        return new TVillageCompanySubsidy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanySubsidy rename(String name) {
        return new TVillageCompanySubsidy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanySubsidy rename(Name name) {
        return new TVillageCompanySubsidy(name, null);
    }
}
