/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TVillageCompanyKnowledgeRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 村站采集的公司知识产权信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillageCompanyKnowledge extends TableImpl<TVillageCompanyKnowledgeRecord> {

    private static final long serialVersionUID = -363648917;

    /**
     * The reference instance of <code>ndt.t_village_company_knowledge</code>
     */
    public static final TVillageCompanyKnowledge T_VILLAGE_COMPANY_KNOWLEDGE = new TVillageCompanyKnowledge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVillageCompanyKnowledgeRecord> getRecordType() {
        return TVillageCompanyKnowledgeRecord.class;
    }

    /**
     * The column <code>ndt.t_village_company_knowledge.id</code>.
     */
    public final TableField<TVillageCompanyKnowledgeRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_village_company_knowledge.village_company_info_id</code>. 公司详情ID
     */
    public final TableField<TVillageCompanyKnowledgeRecord, BigDecimal> VILLAGE_COMPANY_INFO_ID = createField("village_company_info_id", org.jooq.impl.SQLDataType.NUMERIC, this, "公司详情ID");

    /**
     * The column <code>ndt.t_village_company_knowledge.name</code>. 产权名称
     */
    public final TableField<TVillageCompanyKnowledgeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "产权名称");

    /**
     * The column <code>ndt.t_village_company_knowledge.award_date</code>. 颁发时间
     */
    public final TableField<TVillageCompanyKnowledgeRecord, String> AWARD_DATE = createField("award_date", org.jooq.impl.SQLDataType.VARCHAR(50), this, "颁发时间");

    /**
     * The column <code>ndt.t_village_company_knowledge.registration_number</code>. 登记号
     */
    public final TableField<TVillageCompanyKnowledgeRecord, String> REGISTRATION_NUMBER = createField("registration_number", org.jooq.impl.SQLDataType.VARCHAR(50), this, "登记号");

    /**
     * The column <code>ndt.t_village_company_knowledge.state</code>.
     */
    public final TableField<TVillageCompanyKnowledgeRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ndt.t_village_company_knowledge.status</code>.
     */
    public final TableField<TVillageCompanyKnowledgeRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>ndt.t_village_company_knowledge.create_user</code>.
     */
    public final TableField<TVillageCompanyKnowledgeRecord, BigDecimal> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_knowledge.create_time</code>.
     */
    public final TableField<TVillageCompanyKnowledgeRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ndt.t_village_company_knowledge.update_user</code>.
     */
    public final TableField<TVillageCompanyKnowledgeRecord, BigDecimal> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_knowledge.update_time</code>.
     */
    public final TableField<TVillageCompanyKnowledgeRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>ndt.t_village_company_knowledge</code> table reference
     */
    public TVillageCompanyKnowledge() {
        this(DSL.name("t_village_company_knowledge"), null);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_knowledge</code> table reference
     */
    public TVillageCompanyKnowledge(String alias) {
        this(DSL.name(alias), T_VILLAGE_COMPANY_KNOWLEDGE);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_knowledge</code> table reference
     */
    public TVillageCompanyKnowledge(Name alias) {
        this(alias, T_VILLAGE_COMPANY_KNOWLEDGE);
    }

    private TVillageCompanyKnowledge(Name alias, Table<TVillageCompanyKnowledgeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVillageCompanyKnowledge(Name alias, Table<TVillageCompanyKnowledgeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "村站采集的公司知识产权信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_VILLAGE_COMPANY_KNOWLEDGE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TVillageCompanyKnowledgeRecord> getPrimaryKey() {
        return Keys.T_VILLAGE_COMPANY_KNOWLEDGE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TVillageCompanyKnowledgeRecord>> getKeys() {
        return Arrays.<UniqueKey<TVillageCompanyKnowledgeRecord>>asList(Keys.T_VILLAGE_COMPANY_KNOWLEDGE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledge as(String alias) {
        return new TVillageCompanyKnowledge(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledge as(Name alias) {
        return new TVillageCompanyKnowledge(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanyKnowledge rename(String name) {
        return new TVillageCompanyKnowledge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanyKnowledge rename(Name name) {
        return new TVillageCompanyKnowledge(name, null);
    }
}
