/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TVillagePersonalInsuredRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 政策性保险参保信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillagePersonalInsured extends TableImpl<TVillagePersonalInsuredRecord> {

    private static final long serialVersionUID = 1021796886;

    /**
     * The reference instance of <code>ndt.t_village_personal_insured</code>
     */
    public static final TVillagePersonalInsured T_VILLAGE_PERSONAL_INSURED = new TVillagePersonalInsured();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVillagePersonalInsuredRecord> getRecordType() {
        return TVillagePersonalInsuredRecord.class;
    }

    /**
     * The column <code>ndt.t_village_personal_insured.id</code>.
     */
    public final TableField<TVillagePersonalInsuredRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_village_personal_insured.baseinfo_id</code>. 对应用户基本信息id
     */
    public final TableField<TVillagePersonalInsuredRecord, BigDecimal> BASEINFO_ID = createField("baseinfo_id", org.jooq.impl.SQLDataType.NUMERIC, this, "对应用户基本信息id");

    /**
     * The column <code>ndt.t_village_personal_insured.insured_type</code>. 参加保险类型
     */
    public final TableField<TVillagePersonalInsuredRecord, String> INSURED_TYPE = createField("insured_type", org.jooq.impl.SQLDataType.VARCHAR(80), this, "参加保险类型");

    /**
     * The column <code>ndt.t_village_personal_insured.insured_amount</code>. 保险金额(元)
     */
    public final TableField<TVillagePersonalInsuredRecord, BigDecimal> INSURED_AMOUNT = createField("insured_amount", org.jooq.impl.SQLDataType.NUMERIC, this, "保险金额(元)");

    /**
     * The column <code>ndt.t_village_personal_insured.insured_start_time</code>. 参保日期
     */
    public final TableField<TVillagePersonalInsuredRecord, String> INSURED_START_TIME = createField("insured_start_time", org.jooq.impl.SQLDataType.VARCHAR(50), this, "参保日期");

    /**
     * The column <code>ndt.t_village_personal_insured.insured_end_time</code>. 保险到期日期
     */
    public final TableField<TVillagePersonalInsuredRecord, String> INSURED_END_TIME = createField("insured_end_time", org.jooq.impl.SQLDataType.VARCHAR(50), this, "保险到期日期");

    /**
     * The column <code>ndt.t_village_personal_insured.status</code>.
     */
    public final TableField<TVillagePersonalInsuredRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>ndt.t_village_personal_insured.create_user</code>.
     */
    public final TableField<TVillagePersonalInsuredRecord, BigDecimal> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_personal_insured.create_time</code>.
     */
    public final TableField<TVillagePersonalInsuredRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ndt.t_village_personal_insured.update_user</code>.
     */
    public final TableField<TVillagePersonalInsuredRecord, BigDecimal> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_personal_insured.update_time</code>.
     */
    public final TableField<TVillagePersonalInsuredRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>ndt.t_village_personal_insured</code> table reference
     */
    public TVillagePersonalInsured() {
        this(DSL.name("t_village_personal_insured"), null);
    }

    /**
     * Create an aliased <code>ndt.t_village_personal_insured</code> table reference
     */
    public TVillagePersonalInsured(String alias) {
        this(DSL.name(alias), T_VILLAGE_PERSONAL_INSURED);
    }

    /**
     * Create an aliased <code>ndt.t_village_personal_insured</code> table reference
     */
    public TVillagePersonalInsured(Name alias) {
        this(alias, T_VILLAGE_PERSONAL_INSURED);
    }

    private TVillagePersonalInsured(Name alias, Table<TVillagePersonalInsuredRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVillagePersonalInsured(Name alias, Table<TVillagePersonalInsuredRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "政策性保险参保信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_VILLAGE_PERSONAL_INSURED_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TVillagePersonalInsuredRecord> getPrimaryKey() {
        return Keys.T_VILLAGE_PERSONAL_INSURED_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TVillagePersonalInsuredRecord>> getKeys() {
        return Arrays.<UniqueKey<TVillagePersonalInsuredRecord>>asList(Keys.T_VILLAGE_PERSONAL_INSURED_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalInsured as(String alias) {
        return new TVillagePersonalInsured(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalInsured as(Name alias) {
        return new TVillagePersonalInsured(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillagePersonalInsured rename(String name) {
        return new TVillagePersonalInsured(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillagePersonalInsured rename(Name name) {
        return new TVillagePersonalInsured(name, null);
    }
}
