/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TVillageCompanyFinanceRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 村站采集的公司年度财务表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillageCompanyFinance extends TableImpl<TVillageCompanyFinanceRecord> {

    private static final long serialVersionUID = -1211322095;

    /**
     * The reference instance of <code>ndt.t_village_company_finance</code>
     */
    public static final TVillageCompanyFinance T_VILLAGE_COMPANY_FINANCE = new TVillageCompanyFinance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVillageCompanyFinanceRecord> getRecordType() {
        return TVillageCompanyFinanceRecord.class;
    }

    /**
     * The column <code>ndt.t_village_company_finance.id</code>.
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_village_company_finance.village_company_info_id</code>. 公司详情ID
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> VILLAGE_COMPANY_INFO_ID = createField("village_company_info_id", org.jooq.impl.SQLDataType.NUMERIC, this, "公司详情ID");

    /**
     * The column <code>ndt.t_village_company_finance.calendar_year</code>. 年度
     */
    public final TableField<TVillageCompanyFinanceRecord, String> CALENDAR_YEAR = createField("calendar_year", org.jooq.impl.SQLDataType.VARCHAR(30), this, "年度");

    /**
     * The column <code>ndt.t_village_company_finance.income_amt</code>. 总收入
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> INCOME_AMT = createField("income_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "总收入");

    /**
     * The column <code>ndt.t_village_company_finance.employee_number</code>. 雇员数
     */
    public final TableField<TVillageCompanyFinanceRecord, Integer> EMPLOYEE_NUMBER = createField("employee_number", org.jooq.impl.SQLDataType.INTEGER, this, "雇员数");

    /**
     * The column <code>ndt.t_village_company_finance.finance_data</code>. 主要财务数据
     */
    public final TableField<TVillageCompanyFinanceRecord, String> FINANCE_DATA = createField("finance_data", org.jooq.impl.SQLDataType.VARCHAR(200), this, "主要财务数据");

    /**
     * The column <code>ndt.t_village_company_finance.total_asset_amt</code>. 总资产
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> TOTAL_ASSET_AMT = createField("total_asset_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "总资产");

    /**
     * The column <code>ndt.t_village_company_finance.net_asset_amt</code>. 净资产
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> NET_ASSET_AMT = createField("net_asset_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "净资产");

    /**
     * The column <code>ndt.t_village_company_finance.main_business</code>. 主业务
     */
    public final TableField<TVillageCompanyFinanceRecord, String> MAIN_BUSINESS = createField("main_business", org.jooq.impl.SQLDataType.VARCHAR(200), this, "主业务");

    /**
     * The column <code>ndt.t_village_company_finance.main_business_amt</code>. 主业务收入
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> MAIN_BUSINESS_AMT = createField("main_business_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "主业务收入");

    /**
     * The column <code>ndt.t_village_company_finance.net_profit_amt</code>. 净利润
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> NET_PROFIT_AMT = createField("net_profit_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "净利润");

    /**
     * The column <code>ndt.t_village_company_finance.gross_profit_amt</code>. 毛利润
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> GROSS_PROFIT_AMT = createField("gross_profit_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "毛利润");

    /**
     * The column <code>ndt.t_village_company_finance.tax_amt</code>. 纳税额
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> TAX_AMT = createField("tax_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "纳税额");

    /**
     * The column <code>ndt.t_village_company_finance.debt_amt</code>. 负债额
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> DEBT_AMT = createField("debt_amt", org.jooq.impl.SQLDataType.NUMERIC, this, "负债额");

    /**
     * The column <code>ndt.t_village_company_finance.loan_balance</code>. 贷款余额
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> LOAN_BALANCE = createField("loan_balance", org.jooq.impl.SQLDataType.NUMERIC, this, "贷款余额");

    /**
     * The column <code>ndt.t_village_company_finance.creditor_number</code>. 债权人数量
     */
    public final TableField<TVillageCompanyFinanceRecord, Integer> CREDITOR_NUMBER = createField("creditor_number", org.jooq.impl.SQLDataType.INTEGER, this, "债权人数量");

    /**
     * The column <code>ndt.t_village_company_finance.owner_equity</code>. 所有者权益
     */
    public final TableField<TVillageCompanyFinanceRecord, String> OWNER_EQUITY = createField("owner_equity", org.jooq.impl.SQLDataType.VARCHAR(50), this, "所有者权益");

    /**
     * The column <code>ndt.t_village_company_finance.status</code>.
     */
    public final TableField<TVillageCompanyFinanceRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>ndt.t_village_company_finance.create_user</code>.
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_finance.create_time</code>.
     */
    public final TableField<TVillageCompanyFinanceRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ndt.t_village_company_finance.update_user</code>.
     */
    public final TableField<TVillageCompanyFinanceRecord, BigDecimal> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_company_finance.update_time</code>.
     */
    public final TableField<TVillageCompanyFinanceRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>ndt.t_village_company_finance</code> table reference
     */
    public TVillageCompanyFinance() {
        this(DSL.name("t_village_company_finance"), null);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_finance</code> table reference
     */
    public TVillageCompanyFinance(String alias) {
        this(DSL.name(alias), T_VILLAGE_COMPANY_FINANCE);
    }

    /**
     * Create an aliased <code>ndt.t_village_company_finance</code> table reference
     */
    public TVillageCompanyFinance(Name alias) {
        this(alias, T_VILLAGE_COMPANY_FINANCE);
    }

    private TVillageCompanyFinance(Name alias, Table<TVillageCompanyFinanceRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVillageCompanyFinance(Name alias, Table<TVillageCompanyFinanceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "村站采集的公司年度财务表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_VILLAGE_COMPANY_FINANCE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TVillageCompanyFinanceRecord> getPrimaryKey() {
        return Keys.T_VILLAGE_COMPANY_FINANCE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TVillageCompanyFinanceRecord>> getKeys() {
        return Arrays.<UniqueKey<TVillageCompanyFinanceRecord>>asList(Keys.T_VILLAGE_COMPANY_FINANCE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyFinance as(String alias) {
        return new TVillageCompanyFinance(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyFinance as(Name alias) {
        return new TVillageCompanyFinance(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanyFinance rename(String name) {
        return new TVillageCompanyFinance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillageCompanyFinance rename(Name name) {
        return new TVillageCompanyFinance(name, null);
    }
}
