/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables;


import com.ndt.sms.entity.Indexes;
import com.ndt.sms.entity.Keys;
import com.ndt.sms.entity.Ndt;
import com.ndt.sms.entity.tables.records.TVillagePersonalEquipmentRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 设备信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillagePersonalEquipment extends TableImpl<TVillagePersonalEquipmentRecord> {

    private static final long serialVersionUID = -176859621;

    /**
     * The reference instance of <code>ndt.t_village_personal_equipment</code>
     */
    public static final TVillagePersonalEquipment T_VILLAGE_PERSONAL_EQUIPMENT = new TVillagePersonalEquipment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVillagePersonalEquipmentRecord> getRecordType() {
        return TVillagePersonalEquipmentRecord.class;
    }

    /**
     * The column <code>ndt.t_village_personal_equipment.id</code>.
     */
    public final TableField<TVillagePersonalEquipmentRecord, BigDecimal> ID = createField("id", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>ndt.t_village_personal_equipment.baseinfo_id</code>. 对应用户基本信息id
     */
    public final TableField<TVillagePersonalEquipmentRecord, BigDecimal> BASEINFO_ID = createField("baseinfo_id", org.jooq.impl.SQLDataType.NUMERIC, this, "对应用户基本信息id");

    /**
     * The column <code>ndt.t_village_personal_equipment.equipment_type</code>. 生产及运输设备种类
     */
    public final TableField<TVillagePersonalEquipmentRecord, String> EQUIPMENT_TYPE = createField("equipment_type", org.jooq.impl.SQLDataType.VARCHAR(80), this, "生产及运输设备种类");

    /**
     * The column <code>ndt.t_village_personal_equipment.equipment_amount</code>. 购进价格
     */
    public final TableField<TVillagePersonalEquipmentRecord, BigDecimal> EQUIPMENT_AMOUNT = createField("equipment_amount", org.jooq.impl.SQLDataType.NUMERIC, this, "购进价格");

    /**
     * The column <code>ndt.t_village_personal_equipment.buy_equipment_time</code>. 购进年月
     */
    public final TableField<TVillagePersonalEquipmentRecord, String> BUY_EQUIPMENT_TIME = createField("buy_equipment_time", org.jooq.impl.SQLDataType.VARCHAR(50), this, "购进年月");

    /**
     * The column <code>ndt.t_village_personal_equipment.status</code>.
     */
    public final TableField<TVillagePersonalEquipmentRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>ndt.t_village_personal_equipment.create_user</code>.
     */
    public final TableField<TVillagePersonalEquipmentRecord, BigDecimal> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_personal_equipment.create_time</code>.
     */
    public final TableField<TVillagePersonalEquipmentRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ndt.t_village_personal_equipment.update_user</code>.
     */
    public final TableField<TVillagePersonalEquipmentRecord, BigDecimal> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ndt.t_village_personal_equipment.update_time</code>.
     */
    public final TableField<TVillagePersonalEquipmentRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>ndt.t_village_personal_equipment</code> table reference
     */
    public TVillagePersonalEquipment() {
        this(DSL.name("t_village_personal_equipment"), null);
    }

    /**
     * Create an aliased <code>ndt.t_village_personal_equipment</code> table reference
     */
    public TVillagePersonalEquipment(String alias) {
        this(DSL.name(alias), T_VILLAGE_PERSONAL_EQUIPMENT);
    }

    /**
     * Create an aliased <code>ndt.t_village_personal_equipment</code> table reference
     */
    public TVillagePersonalEquipment(Name alias) {
        this(alias, T_VILLAGE_PERSONAL_EQUIPMENT);
    }

    private TVillagePersonalEquipment(Name alias, Table<TVillagePersonalEquipmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVillagePersonalEquipment(Name alias, Table<TVillagePersonalEquipmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "设备信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ndt.NDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_VILLAGE_PERSONAL_EQUIPMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TVillagePersonalEquipmentRecord> getPrimaryKey() {
        return Keys.T_VILLAGE_PERSONAL_EQUIPMENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TVillagePersonalEquipmentRecord>> getKeys() {
        return Arrays.<UniqueKey<TVillagePersonalEquipmentRecord>>asList(Keys.T_VILLAGE_PERSONAL_EQUIPMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalEquipment as(String alias) {
        return new TVillagePersonalEquipment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalEquipment as(Name alias) {
        return new TVillagePersonalEquipment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillagePersonalEquipment rename(String name) {
        return new TVillagePersonalEquipment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVillagePersonalEquipment rename(Name name) {
        return new TVillagePersonalEquipment(name, null);
    }
}
