/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TBanner;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * t_banner
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBannerRecord extends UpdatableRecordImpl<TBannerRecord> implements Record15<String, Short, BigDecimal, String, Short, String, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp, BigDecimal, Integer, Integer> {

    private static final long serialVersionUID = -407244106;

    /**
     * Setter for <code>ndt.t_banner.division_code</code>. 区域编码
     */
    public TBannerRecord setDivisionCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.division_code</code>. 区域编码
     */
    public String getDivisionCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ndt.t_banner.column</code>. 栏目id
     */
    public TBannerRecord setColumn(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.column</code>. 栏目id
     */
    public Short getColumn() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>ndt.t_banner.id</code>. id
     */
    public TBannerRecord setId(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.id</code>. id
     */
    public BigDecimal getId() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>ndt.t_banner.title</code>. banner图title
     */
    public TBannerRecord setTitle(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.title</code>. banner图title
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ndt.t_banner.type</code>. banner图类型(1、无，2、外链，3、弹窗)
     */
    public TBannerRecord setType(Short value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.type</code>. banner图类型(1、无，2、外链，3、弹窗)
     */
    public Short getType() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>ndt.t_banner.img_url</code>. banner图链接
     */
    public TBannerRecord setImgUrl(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.img_url</code>. banner图链接
     */
    public String getImgUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ndt.t_banner.href</code>. 外链链接
     */
    public TBannerRecord setHref(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.href</code>. 外链链接
     */
    public String getHref() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ndt.t_banner.status</code>. 状态(0、不可用，1、可用)
     */
    public TBannerRecord setStatus(Short value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.status</code>. 状态(0、不可用，1、可用)
     */
    public Short getStatus() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>ndt.t_banner.create_user</code>. 创建人
     */
    public TBannerRecord setCreateUser(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.create_user</code>. 创建人
     */
    public BigDecimal getCreateUser() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>ndt.t_banner.create_time</code>. 创建时间
     */
    public TBannerRecord setCreateTime(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>ndt.t_banner.update_user</code>. 更新人
     */
    public TBannerRecord setUpdateUser(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.update_user</code>. 更新人
     */
    public BigDecimal getUpdateUser() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>ndt.t_banner.update_time</code>. 更新时间
     */
    public TBannerRecord setUpdateTime(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>ndt.t_banner.model_id</code>. 弹窗id
     */
    public TBannerRecord setModelId(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.model_id</code>. 弹窗id
     */
    public BigDecimal getModelId() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>ndt.t_banner.old_sort</code>. 历史排序号
     */
    public TBannerRecord setOldSort(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.old_sort</code>. 历史排序号
     */
    public Integer getOldSort() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>ndt.t_banner.sort</code>. 排序号
     */
    public TBannerRecord setSort(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_banner.sort</code>. 排序号
     */
    public Integer getSort() {
        return (Integer) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, Short, BigDecimal, String, Short, String, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp, BigDecimal, Integer, Integer> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, Short, BigDecimal, String, Short, String, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp, BigDecimal, Integer, Integer> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TBanner.T_BANNER.DIVISION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return TBanner.T_BANNER.COLUMN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return TBanner.T_BANNER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TBanner.T_BANNER.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return TBanner.T_BANNER.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TBanner.T_BANNER.IMG_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TBanner.T_BANNER.HREF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return TBanner.T_BANNER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return TBanner.T_BANNER.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TBanner.T_BANNER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return TBanner.T_BANNER.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return TBanner.T_BANNER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return TBanner.T_BANNER.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TBanner.T_BANNER.OLD_SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return TBanner.T_BANNER.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getDivisionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getColumn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getHref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component13() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getOldSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDivisionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getColumn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getOldSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value1(String value) {
        setDivisionCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value2(Short value) {
        setColumn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value3(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value4(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value5(Short value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value6(String value) {
        setImgUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value7(String value) {
        setHref(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value8(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value9(BigDecimal value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value11(BigDecimal value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value12(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value13(BigDecimal value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value14(Integer value) {
        setOldSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord value15(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBannerRecord values(String value1, Short value2, BigDecimal value3, String value4, Short value5, String value6, String value7, Short value8, BigDecimal value9, Timestamp value10, BigDecimal value11, Timestamp value12, BigDecimal value13, Integer value14, Integer value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TBannerRecord
     */
    public TBannerRecord() {
        super(TBanner.T_BANNER);
    }

    /**
     * Create a detached, initialised TBannerRecord
     */
    public TBannerRecord(String divisionCode, Short column, BigDecimal id, String title, Short type, String imgUrl, String href, Short status, BigDecimal createUser, Timestamp createTime, BigDecimal updateUser, Timestamp updateTime, BigDecimal modelId, Integer oldSort, Integer sort) {
        super(TBanner.T_BANNER);

        set(0, divisionCode);
        set(1, column);
        set(2, id);
        set(3, title);
        set(4, type);
        set(5, imgUrl);
        set(6, href);
        set(7, status);
        set(8, createUser);
        set(9, createTime);
        set(10, updateUser);
        set(11, updateTime);
        set(12, modelId);
        set(13, oldSort);
        set(14, sort);
    }
}
