/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TFile;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文件表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFileRecord extends UpdatableRecordImpl<TFileRecord> implements Record7<BigDecimal, String, String, String, Long, BigDecimal, Timestamp> {

    private static final long serialVersionUID = -1857686598;

    /**
     * Setter for <code>ndt.t_file.id</code>.
     */
    public TFileRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_file.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_file.path</code>. 文件路径
     */
    public TFileRecord setPath(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_file.path</code>. 文件路径
     */
    public String getPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ndt.t_file.name</code>. 文件名
     */
    public TFileRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_file.name</code>. 文件名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ndt.t_file.file_type</code>. 文件类型
     */
    public TFileRecord setFileType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_file.file_type</code>. 文件类型
     */
    public String getFileType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ndt.t_file.size</code>. 文件大小
     */
    public TFileRecord setSize(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_file.size</code>. 文件大小
     */
    public Long getSize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>ndt.t_file.create_by</code>. 创建人
     */
    public TFileRecord setCreateBy(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_file.create_by</code>. 创建人
     */
    public BigDecimal getCreateBy() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>ndt.t_file.create_at</code>. 创建时间
     */
    public TFileRecord setCreateAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_file.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigDecimal, String, String, String, Long, BigDecimal, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigDecimal, String, String, String, Long, BigDecimal, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TFile.T_FILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TFile.T_FILE.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TFile.T_FILE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TFile.T_FILE.FILE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return TFile.T_FILE.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return TFile.T_FILE.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TFile.T_FILE.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFileType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFileType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord value2(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord value4(String value) {
        setFileType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord value5(Long value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord value6(BigDecimal value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord value7(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFileRecord values(BigDecimal value1, String value2, String value3, String value4, Long value5, BigDecimal value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFileRecord
     */
    public TFileRecord() {
        super(TFile.T_FILE);
    }

    /**
     * Create a detached, initialised TFileRecord
     */
    public TFileRecord(BigDecimal id, String path, String name, String fileType, Long size, BigDecimal createBy, Timestamp createAt) {
        super(TFile.T_FILE);

        set(0, id);
        set(1, path);
        set(2, name);
        set(3, fileType);
        set(4, size);
        set(5, createBy);
        set(6, createAt);
    }
}
