/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TLoanproductSyncconfig;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 贷款产品同步配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLoanproductSyncconfigRecord extends UpdatableRecordImpl<TLoanproductSyncconfigRecord> implements Record12<BigDecimal, BigDecimal, String, BigDecimal, String, Boolean, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> {

    private static final long serialVersionUID = -2132802434;

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.id</code>.
     */
    public TLoanproductSyncconfigRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.org_id</code>. 银行id
     */
    public TLoanproductSyncconfigRecord setOrgId(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.org_id</code>. 银行id
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.org_code</code>. 银行代码
     */
    public TLoanproductSyncconfigRecord setOrgCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.org_code</code>. 银行代码
     */
    public String getOrgCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.product_id</code>. 产品id
     */
    public TLoanproductSyncconfigRecord setProductId(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.product_id</code>. 产品id
     */
    public BigDecimal getProductId() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.product_code</code>. 产品代码
     */
    public TLoanproductSyncconfigRecord setProductCode(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.product_code</code>. 产品代码
     */
    public String getProductCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.is_autosync</code>. 是否自动同步
     */
    public TLoanproductSyncconfigRecord setIsAutosync(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.is_autosync</code>. 是否自动同步
     */
    public Boolean getIsAutosync() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.sync_url</code>. 同步请求url
     */
    public TLoanproductSyncconfigRecord setSyncUrl(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.sync_url</code>. 同步请求url
     */
    public String getSyncUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.status</code>.
     */
    public TLoanproductSyncconfigRecord setStatus(Short value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.status</code>.
     */
    public Short getStatus() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.create_by</code>.
     */
    public TLoanproductSyncconfigRecord setCreateBy(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.create_by</code>.
     */
    public BigDecimal getCreateBy() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.create_at</code>.
     */
    public TLoanproductSyncconfigRecord setCreateAt(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.create_at</code>.
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.update_by</code>.
     */
    public TLoanproductSyncconfigRecord setUpdateBy(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.update_by</code>.
     */
    public BigDecimal getUpdateBy() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>ndt.t_loanproduct_syncconfig.update_at</code>.
     */
    public TLoanproductSyncconfigRecord setUpdateAt(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_loanproduct_syncconfig.update_at</code>.
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<BigDecimal, BigDecimal, String, BigDecimal, String, Boolean, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<BigDecimal, BigDecimal, String, BigDecimal, String, Boolean, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.ORG_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.PRODUCT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.IS_AUTOSYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.SYNC_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrgCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getIsAutosync();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSyncUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrgCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsAutosync();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSyncUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value2(BigDecimal value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value3(String value) {
        setOrgCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value4(BigDecimal value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value5(String value) {
        setProductCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value6(Boolean value) {
        setIsAutosync(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value7(String value) {
        setSyncUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value8(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value9(BigDecimal value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value10(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value11(BigDecimal value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord value12(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLoanproductSyncconfigRecord values(BigDecimal value1, BigDecimal value2, String value3, BigDecimal value4, String value5, Boolean value6, String value7, Short value8, BigDecimal value9, Timestamp value10, BigDecimal value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLoanproductSyncconfigRecord
     */
    public TLoanproductSyncconfigRecord() {
        super(TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG);
    }

    /**
     * Create a detached, initialised TLoanproductSyncconfigRecord
     */
    public TLoanproductSyncconfigRecord(BigDecimal id, BigDecimal orgId, String orgCode, BigDecimal productId, String productCode, Boolean isAutosync, String syncUrl, Short status, BigDecimal createBy, Timestamp createAt, BigDecimal updateBy, Timestamp updateAt) {
        super(TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG);

        set(0, id);
        set(1, orgId);
        set(2, orgCode);
        set(3, productId);
        set(4, productCode);
        set(5, isAutosync);
        set(6, syncUrl);
        set(7, status);
        set(8, createBy);
        set(9, createAt);
        set(10, updateBy);
        set(11, updateAt);
    }
}
