/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TRiskshareApply;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 风险分担申请
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRiskshareApplyRecord extends UpdatableRecordImpl<TRiskshareApplyRecord> implements Record19<BigDecimal, BigDecimal, Integer, BigDecimal, Timestamp, BigDecimal, String, BigDecimal, Integer, BigDecimal, BigDecimal, BigDecimal, String, Integer, BigDecimal, Timestamp, BigDecimal, Timestamp, Short> {

    private static final long serialVersionUID = -1483028220;

    /**
     * Setter for <code>ndt.t_riskshare_apply.id</code>.
     */
    public TRiskshareApplyRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.org_id</code>. 申请机构ID,来自于三种金融机构之一
     */
    public TRiskshareApplyRecord setOrgId(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.org_id</code>. 申请机构ID,来自于三种金融机构之一
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.type</code>. 风险资金类型
     */
    public TRiskshareApplyRecord setType(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.type</code>. 风险资金类型
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.loan_apply_id</code>. 申请ID,参考贷款申请主键
     */
    public TRiskshareApplyRecord setLoanApplyId(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.loan_apply_id</code>. 申请ID,参考贷款申请主键
     */
    public BigDecimal getLoanApplyId() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.loan_apply_time</code>. 申请时间,参考贷款申请时间
     */
    public TRiskshareApplyRecord setLoanApplyTime(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.loan_apply_time</code>. 申请时间,参考贷款申请时间
     */
    public Timestamp getLoanApplyTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.invitation_id</code>. 邀约ID,参考贷款邀约主键
     */
    public TRiskshareApplyRecord setInvitationId(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.invitation_id</code>. 邀约ID,参考贷款邀约主键
     */
    public BigDecimal getInvitationId() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.invitation_code</code>. 邀约业务码,参考贷款邀约业务码
     */
    public TRiskshareApplyRecord setInvitationCode(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.invitation_code</code>. 邀约业务码,参考贷款邀约业务码
     */
    public String getInvitationCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.invitation_user_id</code>. 贷款主体ID,参考贷款邀约user_id
     */
    public TRiskshareApplyRecord setInvitationUserId(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.invitation_user_id</code>. 贷款主体ID,参考贷款邀约user_id
     */
    public BigDecimal getInvitationUserId() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.invitation_user_type</code>. 贷款主体类型,参考用户表user_type
     */
    public TRiskshareApplyRecord setInvitationUserType(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.invitation_user_type</code>. 贷款主体类型,参考用户表user_type
     */
    public Integer getInvitationUserType() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.user_admindivision_id</code>. 贷款主体所在区域,参考用户表admindivision_id
     */
    public TRiskshareApplyRecord setUserAdmindivisionId(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.user_admindivision_id</code>. 贷款主体所在区域,参考用户表admindivision_id
     */
    public BigDecimal getUserAdmindivisionId() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.loan_done_amount</code>. 放款金额
     */
    public TRiskshareApplyRecord setLoanDoneAmount(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.loan_done_amount</code>. 放款金额
     */
    public BigDecimal getLoanDoneAmount() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.apply_amount</code>. 申请分担金额
     */
    public TRiskshareApplyRecord setApplyAmount(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.apply_amount</code>. 申请分担金额
     */
    public BigDecimal getApplyAmount() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.files</code>. 申请提供文件
     */
    public TRiskshareApplyRecord setFiles(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.files</code>. 申请提供文件
     */
    public String getFiles() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.state</code>. 分担申请所处阶段
     */
    public TRiskshareApplyRecord setState(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.state</code>. 分担申请所处阶段
     */
    public Integer getState() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.create_user</code>.
     */
    public TRiskshareApplyRecord setCreateUser(BigDecimal value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.create_user</code>.
     */
    public BigDecimal getCreateUser() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.create_time</code>.
     */
    public TRiskshareApplyRecord setCreateTime(Timestamp value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.update_user</code>.
     */
    public TRiskshareApplyRecord setUpdateUser(BigDecimal value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.update_user</code>.
     */
    public BigDecimal getUpdateUser() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.update_time</code>.
     */
    public TRiskshareApplyRecord setUpdateTime(Timestamp value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>ndt.t_riskshare_apply.status</code>.
     */
    public TRiskshareApplyRecord setStatus(Short value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_riskshare_apply.status</code>.
     */
    public Short getStatus() {
        return (Short) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<BigDecimal, BigDecimal, Integer, BigDecimal, Timestamp, BigDecimal, String, BigDecimal, Integer, BigDecimal, BigDecimal, BigDecimal, String, Integer, BigDecimal, Timestamp, BigDecimal, Timestamp, Short> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<BigDecimal, BigDecimal, Integer, BigDecimal, Timestamp, BigDecimal, String, BigDecimal, Integer, BigDecimal, BigDecimal, BigDecimal, String, Integer, BigDecimal, Timestamp, BigDecimal, Timestamp, Short> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TRiskshareApply.T_RISKSHARE_APPLY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TRiskshareApply.T_RISKSHARE_APPLY.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRiskshareApply.T_RISKSHARE_APPLY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TRiskshareApply.T_RISKSHARE_APPLY.LOAN_APPLY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TRiskshareApply.T_RISKSHARE_APPLY.LOAN_APPLY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return TRiskshareApply.T_RISKSHARE_APPLY.INVITATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TRiskshareApply.T_RISKSHARE_APPLY.INVITATION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return TRiskshareApply.T_RISKSHARE_APPLY.INVITATION_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TRiskshareApply.T_RISKSHARE_APPLY.INVITATION_USER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return TRiskshareApply.T_RISKSHARE_APPLY.USER_ADMINDIVISION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return TRiskshareApply.T_RISKSHARE_APPLY.LOAN_DONE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return TRiskshareApply.T_RISKSHARE_APPLY.APPLY_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TRiskshareApply.T_RISKSHARE_APPLY.FILES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TRiskshareApply.T_RISKSHARE_APPLY.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return TRiskshareApply.T_RISKSHARE_APPLY.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return TRiskshareApply.T_RISKSHARE_APPLY.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field17() {
        return TRiskshareApply.T_RISKSHARE_APPLY.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return TRiskshareApply.T_RISKSHARE_APPLY.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field19() {
        return TRiskshareApply.T_RISKSHARE_APPLY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getLoanApplyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLoanApplyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getInvitationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getInvitationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getInvitationUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getInvitationUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getUserAdmindivisionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getLoanDoneAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getApplyAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getFiles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component15() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component17() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component19() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getLoanApplyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLoanApplyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getInvitationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInvitationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getInvitationUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getInvitationUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getUserAdmindivisionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getLoanDoneAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getApplyAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getFiles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value17() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value19() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value2(BigDecimal value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value3(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value4(BigDecimal value) {
        setLoanApplyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value5(Timestamp value) {
        setLoanApplyTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value6(BigDecimal value) {
        setInvitationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value7(String value) {
        setInvitationCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value8(BigDecimal value) {
        setInvitationUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value9(Integer value) {
        setInvitationUserType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value10(BigDecimal value) {
        setUserAdmindivisionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value11(BigDecimal value) {
        setLoanDoneAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value12(BigDecimal value) {
        setApplyAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value13(String value) {
        setFiles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value14(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value15(BigDecimal value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value16(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value17(BigDecimal value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value18(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord value19(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRiskshareApplyRecord values(BigDecimal value1, BigDecimal value2, Integer value3, BigDecimal value4, Timestamp value5, BigDecimal value6, String value7, BigDecimal value8, Integer value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, String value13, Integer value14, BigDecimal value15, Timestamp value16, BigDecimal value17, Timestamp value18, Short value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRiskshareApplyRecord
     */
    public TRiskshareApplyRecord() {
        super(TRiskshareApply.T_RISKSHARE_APPLY);
    }

    /**
     * Create a detached, initialised TRiskshareApplyRecord
     */
    public TRiskshareApplyRecord(BigDecimal id, BigDecimal orgId, Integer type, BigDecimal loanApplyId, Timestamp loanApplyTime, BigDecimal invitationId, String invitationCode, BigDecimal invitationUserId, Integer invitationUserType, BigDecimal userAdmindivisionId, BigDecimal loanDoneAmount, BigDecimal applyAmount, String files, Integer state, BigDecimal createUser, Timestamp createTime, BigDecimal updateUser, Timestamp updateTime, Short status) {
        super(TRiskshareApply.T_RISKSHARE_APPLY);

        set(0, id);
        set(1, orgId);
        set(2, type);
        set(3, loanApplyId);
        set(4, loanApplyTime);
        set(5, invitationId);
        set(6, invitationCode);
        set(7, invitationUserId);
        set(8, invitationUserType);
        set(9, userAdmindivisionId);
        set(10, loanDoneAmount);
        set(11, applyAmount);
        set(12, files);
        set(13, state);
        set(14, createUser);
        set(15, createTime);
        set(16, updateUser);
        set(17, updateTime);
        set(18, status);
    }
}
