/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TTermBase;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 项目大类型
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTermBaseRecord extends UpdatableRecordImpl<TTermBaseRecord> implements Record6<BigDecimal, BigDecimal, String, BigDecimal, Short, BigDecimal> {

    private static final long serialVersionUID = 1753897088;

    /**
     * Setter for <code>ndt.t_term_base.id</code>. 主键
     */
    public TTermBaseRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_term_base.id</code>. 主键
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_term_base.term_type_code</code>. 项目类型code
     */
    public TTermBaseRecord setTermTypeCode(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_term_base.term_type_code</code>. 项目类型code
     */
    public BigDecimal getTermTypeCode() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>ndt.t_term_base.term_type_name</code>. 项目类型名称
     */
    public TTermBaseRecord setTermTypeName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_term_base.term_type_name</code>. 项目类型名称
     */
    public String getTermTypeName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ndt.t_term_base.parent_code</code>. 父类型ID
     */
    public TTermBaseRecord setParentCode(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_term_base.parent_code</code>. 父类型ID
     */
    public BigDecimal getParentCode() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>ndt.t_term_base.level</code>. 等级
     */
    public TTermBaseRecord setLevel(Short value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_term_base.level</code>. 等级
     */
    public Short getLevel() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>ndt.t_term_base.discount_scale</code>. 贴息比例
     */
    public TTermBaseRecord setDiscountScale(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_term_base.discount_scale</code>. 贴息比例
     */
    public BigDecimal getDiscountScale() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<BigDecimal, BigDecimal, String, BigDecimal, Short, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<BigDecimal, BigDecimal, String, BigDecimal, Short, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TTermBase.T_TERM_BASE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TTermBase.T_TERM_BASE.TERM_TYPE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TTermBase.T_TERM_BASE.TERM_TYPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TTermBase.T_TERM_BASE.PARENT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return TTermBase.T_TERM_BASE.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return TTermBase.T_TERM_BASE.DISCOUNT_SCALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getTermTypeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTermTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getParentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component5() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getDiscountScale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getTermTypeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTermTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getParentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getDiscountScale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTermBaseRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTermBaseRecord value2(BigDecimal value) {
        setTermTypeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTermBaseRecord value3(String value) {
        setTermTypeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTermBaseRecord value4(BigDecimal value) {
        setParentCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTermBaseRecord value5(Short value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTermBaseRecord value6(BigDecimal value) {
        setDiscountScale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTermBaseRecord values(BigDecimal value1, BigDecimal value2, String value3, BigDecimal value4, Short value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TTermBaseRecord
     */
    public TTermBaseRecord() {
        super(TTermBase.T_TERM_BASE);
    }

    /**
     * Create a detached, initialised TTermBaseRecord
     */
    public TTermBaseRecord(BigDecimal id, BigDecimal termTypeCode, String termTypeName, BigDecimal parentCode, Short level, BigDecimal discountScale) {
        super(TTermBase.T_TERM_BASE);

        set(0, id);
        set(1, termTypeCode);
        set(2, termTypeName);
        set(3, parentCode);
        set(4, level);
        set(5, discountScale);
    }
}
