/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TVillageCompanyKnowledge;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 村站采集的公司知识产权信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillageCompanyKnowledgeRecord extends UpdatableRecordImpl<TVillageCompanyKnowledgeRecord> implements Record11<BigDecimal, BigDecimal, String, String, String, Integer, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> {

    private static final long serialVersionUID = -1160450098;

    /**
     * Setter for <code>ndt.t_village_company_knowledge.id</code>.
     */
    public TVillageCompanyKnowledgeRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.village_company_info_id</code>. 公司详情ID
     */
    public TVillageCompanyKnowledgeRecord setVillageCompanyInfoId(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.village_company_info_id</code>. 公司详情ID
     */
    public BigDecimal getVillageCompanyInfoId() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.name</code>. 产权名称
     */
    public TVillageCompanyKnowledgeRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.name</code>. 产权名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.award_date</code>. 颁发时间
     */
    public TVillageCompanyKnowledgeRecord setAwardDate(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.award_date</code>. 颁发时间
     */
    public String getAwardDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.registration_number</code>. 登记号
     */
    public TVillageCompanyKnowledgeRecord setRegistrationNumber(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.registration_number</code>. 登记号
     */
    public String getRegistrationNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.state</code>.
     */
    public TVillageCompanyKnowledgeRecord setState(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.state</code>.
     */
    public Integer getState() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.status</code>.
     */
    public TVillageCompanyKnowledgeRecord setStatus(Short value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.status</code>.
     */
    public Short getStatus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.create_user</code>.
     */
    public TVillageCompanyKnowledgeRecord setCreateUser(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.create_user</code>.
     */
    public BigDecimal getCreateUser() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.create_time</code>.
     */
    public TVillageCompanyKnowledgeRecord setCreateTime(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.update_user</code>.
     */
    public TVillageCompanyKnowledgeRecord setUpdateUser(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.update_user</code>.
     */
    public BigDecimal getUpdateUser() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>ndt.t_village_company_knowledge.update_time</code>.
     */
    public TVillageCompanyKnowledgeRecord setUpdateTime(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_knowledge.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<BigDecimal, BigDecimal, String, String, String, Integer, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<BigDecimal, BigDecimal, String, String, String, Integer, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.VILLAGE_COMPANY_INFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.AWARD_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.REGISTRATION_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getVillageCompanyInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAwardDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRegistrationNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getVillageCompanyInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAwardDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRegistrationNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value2(BigDecimal value) {
        setVillageCompanyInfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value4(String value) {
        setAwardDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value5(String value) {
        setRegistrationNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value6(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value7(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value8(BigDecimal value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value10(BigDecimal value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyKnowledgeRecord values(BigDecimal value1, BigDecimal value2, String value3, String value4, String value5, Integer value6, Short value7, BigDecimal value8, Timestamp value9, BigDecimal value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TVillageCompanyKnowledgeRecord
     */
    public TVillageCompanyKnowledgeRecord() {
        super(TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE);
    }

    /**
     * Create a detached, initialised TVillageCompanyKnowledgeRecord
     */
    public TVillageCompanyKnowledgeRecord(BigDecimal id, BigDecimal villageCompanyInfoId, String name, String awardDate, String registrationNumber, Integer state, Short status, BigDecimal createUser, Timestamp createTime, BigDecimal updateUser, Timestamp updateTime) {
        super(TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE);

        set(0, id);
        set(1, villageCompanyInfoId);
        set(2, name);
        set(3, awardDate);
        set(4, registrationNumber);
        set(5, state);
        set(6, status);
        set(7, createUser);
        set(8, createTime);
        set(9, updateUser);
        set(10, updateTime);
    }
}
