/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TVillagePersonalPurchasing;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 采购信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillagePersonalPurchasingRecord extends UpdatableRecordImpl<TVillagePersonalPurchasingRecord> implements Record11<BigDecimal, BigDecimal, String, BigDecimal, String, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> {

    private static final long serialVersionUID = -113288335;

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.id</code>.
     */
    public TVillagePersonalPurchasingRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.baseinfo_id</code>. 对应用户基本信息id
     */
    public TVillagePersonalPurchasingRecord setBaseinfoId(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.baseinfo_id</code>. 对应用户基本信息id
     */
    public BigDecimal getBaseinfoId() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.purchasing_commodity</code>. 采购物资
     */
    public TVillagePersonalPurchasingRecord setPurchasingCommodity(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.purchasing_commodity</code>. 采购物资
     */
    public String getPurchasingCommodity() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.purchasing_amount</code>. 采购金额
     */
    public TVillagePersonalPurchasingRecord setPurchasingAmount(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.purchasing_amount</code>. 采购金额
     */
    public BigDecimal getPurchasingAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.purchasing_time</code>. 采购时间
     */
    public TVillagePersonalPurchasingRecord setPurchasingTime(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.purchasing_time</code>. 采购时间
     */
    public String getPurchasingTime() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.purchasing_image_url</code>. 采购相关图片路径
     */
    public TVillagePersonalPurchasingRecord setPurchasingImageUrl(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.purchasing_image_url</code>. 采购相关图片路径
     */
    public String getPurchasingImageUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.status</code>.
     */
    public TVillagePersonalPurchasingRecord setStatus(Short value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.status</code>.
     */
    public Short getStatus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.create_user</code>.
     */
    public TVillagePersonalPurchasingRecord setCreateUser(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.create_user</code>.
     */
    public BigDecimal getCreateUser() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.create_time</code>.
     */
    public TVillagePersonalPurchasingRecord setCreateTime(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.update_user</code>.
     */
    public TVillagePersonalPurchasingRecord setUpdateUser(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.update_user</code>.
     */
    public BigDecimal getUpdateUser() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>ndt.t_village_personal_purchasing.update_time</code>.
     */
    public TVillagePersonalPurchasingRecord setUpdateTime(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_purchasing.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<BigDecimal, BigDecimal, String, BigDecimal, String, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<BigDecimal, BigDecimal, String, BigDecimal, String, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.BASEINFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.PURCHASING_COMMODITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.PURCHASING_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.PURCHASING_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.PURCHASING_IMAGE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getBaseinfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPurchasingCommodity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getPurchasingAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPurchasingTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPurchasingImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getBaseinfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPurchasingCommodity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPurchasingAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPurchasingTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPurchasingImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value2(BigDecimal value) {
        setBaseinfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value3(String value) {
        setPurchasingCommodity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value4(BigDecimal value) {
        setPurchasingAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value5(String value) {
        setPurchasingTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value6(String value) {
        setPurchasingImageUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value7(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value8(BigDecimal value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value10(BigDecimal value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalPurchasingRecord values(BigDecimal value1, BigDecimal value2, String value3, BigDecimal value4, String value5, String value6, Short value7, BigDecimal value8, Timestamp value9, BigDecimal value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TVillagePersonalPurchasingRecord
     */
    public TVillagePersonalPurchasingRecord() {
        super(TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING);
    }

    /**
     * Create a detached, initialised TVillagePersonalPurchasingRecord
     */
    public TVillagePersonalPurchasingRecord(BigDecimal id, BigDecimal baseinfoId, String purchasingCommodity, BigDecimal purchasingAmount, String purchasingTime, String purchasingImageUrl, Short status, BigDecimal createUser, Timestamp createTime, BigDecimal updateUser, Timestamp updateTime) {
        super(TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING);

        set(0, id);
        set(1, baseinfoId);
        set(2, purchasingCommodity);
        set(3, purchasingAmount);
        set(4, purchasingTime);
        set(5, purchasingImageUrl);
        set(6, status);
        set(7, createUser);
        set(8, createTime);
        set(9, updateUser);
        set(10, updateTime);
    }
}
