/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TVillagePersonalHouse;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 房屋资产信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillagePersonalHouseRecord extends UpdatableRecordImpl<TVillagePersonalHouseRecord> implements Record11<BigDecimal, BigDecimal, String, Integer, String, Integer, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> {

    private static final long serialVersionUID = -487388896;

    /**
     * Setter for <code>ndt.t_village_personal_house.id</code>.
     */
    public TVillagePersonalHouseRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.baseinfo_id</code>. 对应用户基本信息id
     */
    public TVillagePersonalHouseRecord setBaseinfoId(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.baseinfo_id</code>. 对应用户基本信息id
     */
    public BigDecimal getBaseinfoId() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.house_address</code>. 房屋地址
     */
    public TVillagePersonalHouseRecord setHouseAddress(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.house_address</code>. 房屋地址
     */
    public String getHouseAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.house_type</code>. 房屋性质，参考码表54
     */
    public TVillagePersonalHouseRecord setHouseType(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.house_type</code>. 房屋性质，参考码表54
     */
    public Integer getHouseType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.house_time</code>. 购建年月
     */
    public TVillagePersonalHouseRecord setHouseTime(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.house_time</code>. 购建年月
     */
    public String getHouseTime() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.floorage</code>. 建筑面积平方米
     */
    public TVillagePersonalHouseRecord setFloorage(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.floorage</code>. 建筑面积平方米
     */
    public Integer getFloorage() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.status</code>.
     */
    public TVillagePersonalHouseRecord setStatus(Short value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.status</code>.
     */
    public Short getStatus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.create_user</code>.
     */
    public TVillagePersonalHouseRecord setCreateUser(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.create_user</code>.
     */
    public BigDecimal getCreateUser() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.create_time</code>.
     */
    public TVillagePersonalHouseRecord setCreateTime(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.update_user</code>.
     */
    public TVillagePersonalHouseRecord setUpdateUser(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.update_user</code>.
     */
    public BigDecimal getUpdateUser() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>ndt.t_village_personal_house.update_time</code>.
     */
    public TVillagePersonalHouseRecord setUpdateTime(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_personal_house.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<BigDecimal, BigDecimal, String, Integer, String, Integer, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<BigDecimal, BigDecimal, String, Integer, String, Integer, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.BASEINFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.HOUSE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.HOUSE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.HOUSE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.FLOORAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getBaseinfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getHouseAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getHouseType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getHouseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getFloorage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getBaseinfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getHouseAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getHouseType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHouseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFloorage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value2(BigDecimal value) {
        setBaseinfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value3(String value) {
        setHouseAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value4(Integer value) {
        setHouseType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value5(String value) {
        setHouseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value6(Integer value) {
        setFloorage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value7(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value8(BigDecimal value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value10(BigDecimal value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillagePersonalHouseRecord values(BigDecimal value1, BigDecimal value2, String value3, Integer value4, String value5, Integer value6, Short value7, BigDecimal value8, Timestamp value9, BigDecimal value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TVillagePersonalHouseRecord
     */
    public TVillagePersonalHouseRecord() {
        super(TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE);
    }

    /**
     * Create a detached, initialised TVillagePersonalHouseRecord
     */
    public TVillagePersonalHouseRecord(BigDecimal id, BigDecimal baseinfoId, String houseAddress, Integer houseType, String houseTime, Integer floorage, Short status, BigDecimal createUser, Timestamp createTime, BigDecimal updateUser, Timestamp updateTime) {
        super(TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE);

        set(0, id);
        set(1, baseinfoId);
        set(2, houseAddress);
        set(3, houseType);
        set(4, houseTime);
        set(5, floorage);
        set(6, status);
        set(7, createUser);
        set(8, createTime);
        set(9, updateUser);
        set(10, updateTime);
    }
}
