/*
 * This file is generated by jOOQ.
*/
package com.ndt.sms.entity.tables.records;


import com.ndt.sms.entity.tables.TVillageCompanyHonor;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 村站采集的公司荣誉资质
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVillageCompanyHonorRecord extends UpdatableRecordImpl<TVillageCompanyHonorRecord> implements Record13<BigDecimal, BigDecimal, Integer, String, String, String, Integer, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> {

    private static final long serialVersionUID = 1341430889;

    /**
     * Setter for <code>ndt.t_village_company_honor.id</code>.
     */
    public TVillageCompanyHonorRecord setId(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.village_company_info_id</code>. 公司详情ID
     */
    public TVillageCompanyHonorRecord setVillageCompanyInfoId(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.village_company_info_id</code>. 公司详情ID
     */
    public BigDecimal getVillageCompanyInfoId() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.type</code>. 0荣誉/1资质
     */
    public TVillageCompanyHonorRecord setType(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.type</code>. 0荣誉/1资质
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.honor_name</code>. 荣誉资质名称
     */
    public TVillageCompanyHonorRecord setHonorName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.honor_name</code>. 荣誉资质名称
     */
    public String getHonorName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.honor_no</code>. 编号
     */
    public TVillageCompanyHonorRecord setHonorNo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.honor_no</code>. 编号
     */
    public String getHonorNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.award_unit</code>. 颁发单位
     */
    public TVillageCompanyHonorRecord setAwardUnit(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.award_unit</code>. 颁发单位
     */
    public String getAwardUnit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.level</code>. 级别
     */
    public TVillageCompanyHonorRecord setLevel(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.level</code>. 级别
     */
    public Integer getLevel() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.award_date</code>. 颁发日期
     */
    public TVillageCompanyHonorRecord setAwardDate(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.award_date</code>. 颁发日期
     */
    public String getAwardDate() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.status</code>.
     */
    public TVillageCompanyHonorRecord setStatus(Short value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.status</code>.
     */
    public Short getStatus() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.create_user</code>.
     */
    public TVillageCompanyHonorRecord setCreateUser(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.create_user</code>.
     */
    public BigDecimal getCreateUser() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.create_time</code>.
     */
    public TVillageCompanyHonorRecord setCreateTime(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.update_user</code>.
     */
    public TVillageCompanyHonorRecord setUpdateUser(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.update_user</code>.
     */
    public BigDecimal getUpdateUser() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>ndt.t_village_company_honor.update_time</code>.
     */
    public TVillageCompanyHonorRecord setUpdateTime(Timestamp value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ndt.t_village_company_honor.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<BigDecimal, BigDecimal, Integer, String, String, String, Integer, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<BigDecimal, BigDecimal, Integer, String, String, String, Integer, String, Short, BigDecimal, Timestamp, BigDecimal, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.VILLAGE_COMPANY_INFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.HONOR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.HONOR_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.AWARD_UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.AWARD_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field9() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getVillageCompanyInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getHonorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getHonorNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAwardUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAwardDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getVillageCompanyInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getHonorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHonorNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAwardUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAwardDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value1(BigDecimal value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value2(BigDecimal value) {
        setVillageCompanyInfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value3(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value4(String value) {
        setHonorName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value5(String value) {
        setHonorNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value6(String value) {
        setAwardUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value7(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value8(String value) {
        setAwardDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value9(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value10(BigDecimal value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value11(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value12(BigDecimal value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord value13(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVillageCompanyHonorRecord values(BigDecimal value1, BigDecimal value2, Integer value3, String value4, String value5, String value6, Integer value7, String value8, Short value9, BigDecimal value10, Timestamp value11, BigDecimal value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TVillageCompanyHonorRecord
     */
    public TVillageCompanyHonorRecord() {
        super(TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR);
    }

    /**
     * Create a detached, initialised TVillageCompanyHonorRecord
     */
    public TVillageCompanyHonorRecord(BigDecimal id, BigDecimal villageCompanyInfoId, Integer type, String honorName, String honorNo, String awardUnit, Integer level, String awardDate, Short status, BigDecimal createUser, Timestamp createTime, BigDecimal updateUser, Timestamp updateTime) {
        super(TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR);

        set(0, id);
        set(1, villageCompanyInfoId);
        set(2, type);
        set(3, honorName);
        set(4, honorNo);
        set(5, awardUnit);
        set(6, level);
        set(7, awardDate);
        set(8, status);
        set(9, createUser);
        set(10, createTime);
        set(11, updateUser);
        set(12, updateTime);
    }
}
